baseURL: https://jiayingchen-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Jiaying Chen
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Welcome to Amy's portfolio website! Get to know me better .
    title: Hello, I am Jiaying (Amy) Chen. 
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Glentworth Street 
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: jchen.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 07422597620
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Jiaying Chen
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
  #    - icon: fa-facebook
   #     label: Facebook
   #     url: https://www.facebook.com
      # - icon: fa-instagram
      #   label: Instagram
      #   url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/JiayingChen116
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jiaying-chen-0934/
  image: ''
  name: Jiaying Chen
  navigation:
    button1:
      - name: View My Projects
        url: blogs
    # button2:
    #   - name: Log In
    #     url: '#'
    links:
      - name: Home
        url: '#'
      - name: My biography
        url: blogs/aliquam
      # - name: My projects
      #    url: blogs/tempus
      - name: My resume
        url: blogs/resume
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: me2.jpeg
        subtitle: Learn more about who I am.
        title: Biography
        url: blogs/aliquam
      - image: purple.jpeg
        subtitle: My very first personal project based on R!
        title: Pre-programme Assignment of MAM2022
        url: blogs/tempus
      - image: vaxtrump.jpg
        subtitle: In this project, I collaborated with five group members and conducted analytics on IBM HR data and Vaccination V.S. Election Results. 
        title: Homework 1 
        url: blogs/magna
      - image: ferrate.png
        subtitle: In this project,I mainly worked on worldbank data and investigated the correlation of GDP,fertility rate, life expectancy and education level in different countries worldwide.
        title: Homework 2 
        url: blogs/hw2
      - image: gdpback.jpeg
        subtitle: In this project, I took the callenge to take a further look into the how the percentage of GDP compositions change over time among different countries and gain insights.
        title: Homework 3
        url: blogs/ipsum
      - image: cvimage.png
        subtitle: Feel free to take a look at my resume to learn more about my past working and research experience.
        title: My resume
        url: blogs/resume
  # two:
  #   buttonText: Get Started
  #   enable: yes
  #   subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
  #     \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
  #     condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
  #     pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
  #     Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
  #     amet pharetra et feugiat tempus."
  #   title: Massa libero
  #   url: blogs
