---
title: "Project 1 IBM HR Analytics"
date: '2017-10-31T22:26:09-05:00'
description: In this project, I collaborated with five group members and conducted
  analytics on IBM HR data and look into how factors like education level and job
  title affect income.
draft: no
image: hr2.png
keywords: ''
slug: magna
categories:
- ''
- ''
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<p><em>Author:Jiaying Chen, Yingjin He, Sabrina Seow, Kashish Solanki, Roman Vazquez Lorenzo, Maximilian Stock</em></p>
<pre class="r"><code>hr_dataset &lt;- read_csv(here::here(&quot;data&quot;, &quot;datasets_1067_1925_WA_Fn-UseC_-HR-Employee-Attrition.csv&quot;))
glimpse(hr_dataset)</code></pre>
<pre><code>## Rows: 1,470
## Columns: 35
## $ Age                      &lt;dbl&gt; 41, 49, 37, 33, 27, 32, 59, 30, 38, 36, 35, 2…
## $ Attrition                &lt;chr&gt; &quot;Yes&quot;, &quot;No&quot;, &quot;Yes&quot;, &quot;No&quot;, &quot;No&quot;, &quot;No&quot;, &quot;No&quot;, &quot;…
## $ BusinessTravel           &lt;chr&gt; &quot;Travel_Rarely&quot;, &quot;Travel_Frequently&quot;, &quot;Travel…
## $ DailyRate                &lt;dbl&gt; 1102, 279, 1373, 1392, 591, 1005, 1324, 1358,…
## $ Department               &lt;chr&gt; &quot;Sales&quot;, &quot;Research &amp; Development&quot;, &quot;Research …
## $ DistanceFromHome         &lt;dbl&gt; 1, 8, 2, 3, 2, 2, 3, 24, 23, 27, 16, 15, 26, …
## $ Education                &lt;dbl&gt; 2, 1, 2, 4, 1, 2, 3, 1, 3, 3, 3, 2, 1, 2, 3, …
## $ EducationField           &lt;chr&gt; &quot;Life Sciences&quot;, &quot;Life Sciences&quot;, &quot;Other&quot;, &quot;L…
## $ EmployeeCount            &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
## $ EmployeeNumber           &lt;dbl&gt; 1, 2, 4, 5, 7, 8, 10, 11, 12, 13, 14, 15, 16,…
## $ EnvironmentSatisfaction  &lt;dbl&gt; 2, 3, 4, 4, 1, 4, 3, 4, 4, 3, 1, 4, 1, 2, 3, …
## $ Gender                   &lt;chr&gt; &quot;Female&quot;, &quot;Male&quot;, &quot;Male&quot;, &quot;Female&quot;, &quot;Male&quot;, &quot;…
## $ HourlyRate               &lt;dbl&gt; 94, 61, 92, 56, 40, 79, 81, 67, 44, 94, 84, 4…
## $ JobInvolvement           &lt;dbl&gt; 3, 2, 2, 3, 3, 3, 4, 3, 2, 3, 4, 2, 3, 3, 2, …
## $ JobLevel                 &lt;dbl&gt; 2, 2, 1, 1, 1, 1, 1, 1, 3, 2, 1, 2, 1, 1, 1, …
## $ JobRole                  &lt;chr&gt; &quot;Sales Executive&quot;, &quot;Research Scientist&quot;, &quot;Lab…
## $ JobSatisfaction          &lt;dbl&gt; 4, 2, 3, 3, 2, 4, 1, 3, 3, 3, 2, 3, 3, 4, 3, …
## $ MaritalStatus            &lt;chr&gt; &quot;Single&quot;, &quot;Married&quot;, &quot;Single&quot;, &quot;Married&quot;, &quot;Ma…
## $ MonthlyIncome            &lt;dbl&gt; 5993, 5130, 2090, 2909, 3468, 3068, 2670, 269…
## $ MonthlyRate              &lt;dbl&gt; 19479, 24907, 2396, 23159, 16632, 11864, 9964…
## $ NumCompaniesWorked       &lt;dbl&gt; 8, 1, 6, 1, 9, 0, 4, 1, 0, 6, 0, 0, 1, 0, 5, …
## $ Over18                   &lt;chr&gt; &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, …
## $ OverTime                 &lt;chr&gt; &quot;Yes&quot;, &quot;No&quot;, &quot;Yes&quot;, &quot;Yes&quot;, &quot;No&quot;, &quot;No&quot;, &quot;Yes&quot;,…
## $ PercentSalaryHike        &lt;dbl&gt; 11, 23, 15, 11, 12, 13, 20, 22, 21, 13, 13, 1…
## $ PerformanceRating        &lt;dbl&gt; 3, 4, 3, 3, 3, 3, 4, 4, 4, 3, 3, 3, 3, 3, 3, …
## $ RelationshipSatisfaction &lt;dbl&gt; 1, 4, 2, 3, 4, 3, 1, 2, 2, 2, 3, 4, 4, 3, 2, …
## $ StandardHours            &lt;dbl&gt; 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 8…
## $ StockOptionLevel         &lt;dbl&gt; 0, 1, 0, 0, 1, 0, 3, 1, 0, 2, 1, 0, 1, 1, 0, …
## $ TotalWorkingYears        &lt;dbl&gt; 8, 10, 7, 8, 6, 8, 12, 1, 10, 17, 6, 10, 5, 3…
## $ TrainingTimesLastYear    &lt;dbl&gt; 0, 3, 3, 3, 3, 2, 3, 2, 2, 3, 5, 3, 1, 2, 4, …
## $ WorkLifeBalance          &lt;dbl&gt; 1, 3, 3, 3, 3, 2, 2, 3, 3, 2, 3, 3, 2, 3, 3, …
## $ YearsAtCompany           &lt;dbl&gt; 6, 10, 0, 8, 2, 7, 1, 1, 9, 7, 5, 9, 5, 2, 4,…
## $ YearsInCurrentRole       &lt;dbl&gt; 4, 7, 0, 7, 2, 7, 0, 0, 7, 7, 4, 5, 2, 2, 2, …
## $ YearsSinceLastPromotion  &lt;dbl&gt; 0, 1, 0, 3, 2, 3, 0, 0, 1, 7, 0, 0, 4, 1, 0, …
## $ YearsWithCurrManager     &lt;dbl&gt; 5, 7, 0, 0, 2, 6, 0, 0, 8, 7, 3, 8, 3, 2, 3, …</code></pre>
<pre class="r"><code>head(hr_cleaned)</code></pre>
<pre><code>## # A tibble: 6 × 19
##     age attrition daily_rate department      distance_from_ho… education  gender
##   &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;                       &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt; 
## 1    41 Yes             1102 Sales                           1 College    Female
## 2    49 No               279 Research &amp; Dev…                 8 Below Col… Male  
## 3    37 Yes             1373 Research &amp; Dev…                 2 College    Male  
## 4    33 No              1392 Research &amp; Dev…                 3 Master     Female
## 5    27 No               591 Research &amp; Dev…                 2 Below Col… Male  
## 6    32 No              1005 Research &amp; Dev…                 2 College    Male  
## # … with 12 more variables: job_role &lt;chr&gt;, environment_satisfaction &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, percent_salary_hike &lt;dbl&gt;,
## #   performance_rating &lt;chr&gt;, total_working_years &lt;dbl&gt;,
## #   work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<pre class="r"><code>skim(hr_cleaned)</code></pre>
<table>
<caption><span id="tab:headerHRData">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">hr_cleaned</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">1470</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">19</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">10</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">9</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">attrition</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">department</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">22</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">education</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">6</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">gender</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">job_role</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">7</td>
<td align="right">25</td>
<td align="right">0</td>
<td align="right">9</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">environment_satisfaction</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">9</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">job_satisfaction</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">9</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">marital_status</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">6</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">performance_rating</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">9</td>
<td align="right">11</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">work_life_balance</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">36.92</td>
<td align="right">9.14</td>
<td align="right">18</td>
<td align="right">30</td>
<td align="right">36</td>
<td align="right">43</td>
<td align="right">60</td>
<td align="left">▂▇▇▃▂</td>
</tr>
<tr class="even">
<td align="left">daily_rate</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">802.49</td>
<td align="right">403.51</td>
<td align="right">102</td>
<td align="right">465</td>
<td align="right">802</td>
<td align="right">1157</td>
<td align="right">1499</td>
<td align="left">▇▇▇▇▇</td>
</tr>
<tr class="odd">
<td align="left">distance_from_home</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">9.19</td>
<td align="right">8.11</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">7</td>
<td align="right">14</td>
<td align="right">29</td>
<td align="left">▇▅▂▂▂</td>
</tr>
<tr class="even">
<td align="left">monthly_income</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">6502.93</td>
<td align="right">4707.96</td>
<td align="right">1009</td>
<td align="right">2911</td>
<td align="right">4919</td>
<td align="right">8379</td>
<td align="right">19999</td>
<td align="left">▇▅▂▁▂</td>
</tr>
<tr class="odd">
<td align="left">num_companies_worked</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2.69</td>
<td align="right">2.50</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">4</td>
<td align="right">9</td>
<td align="left">▇▃▂▂▁</td>
</tr>
<tr class="even">
<td align="left">percent_salary_hike</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">15.21</td>
<td align="right">3.66</td>
<td align="right">11</td>
<td align="right">12</td>
<td align="right">14</td>
<td align="right">18</td>
<td align="right">25</td>
<td align="left">▇▅▃▂▁</td>
</tr>
<tr class="odd">
<td align="left">total_working_years</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">11.28</td>
<td align="right">7.78</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">10</td>
<td align="right">15</td>
<td align="right">40</td>
<td align="left">▇▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">years_at_company</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">7.01</td>
<td align="right">6.13</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">5</td>
<td align="right">9</td>
<td align="right">40</td>
<td align="left">▇▂▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">years_since_last_promotion</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2.19</td>
<td align="right">3.22</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">15</td>
<td align="left">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
<p><em>The <code>hr_cleaned</code> dataset holds fictional information of a total of 1470 employees on variables such as the employees’ education, job specifics, performance and attrition. All in all, there are 9 numeric and 10 non-numeric variables</em></p>
<p><em>Given the wide range of information, one can try to make inferences about dependencies among variables. For example, it might be interesting to find out if a combination of variables might be a good predictor for an employee’s decision to leave the company (<code>attrition</code> = Yes).</em></p>
<ul>
<li>How often do people leave the company (<code>attrition</code>)</li>
</ul>
<pre class="r"><code>number_attrition&lt;-hr_cleaned%&gt;%
  group_by(attrition)%&gt;%
  summarize(number_count = count(attrition))%&gt;%
  mutate(perc = number_count/sum(number_count)) #we introduce a second column, namely percent, to represent the count as a percentage of the total

number_attrition</code></pre>
<pre><code>## # A tibble: 2 × 3
##   attrition number_count  perc
##   &lt;chr&gt;            &lt;int&gt; &lt;dbl&gt;
## 1 No                1233 0.839
## 2 Yes                237 0.161</code></pre>
<p><em>Looking at the sheer counts of YES and NO entries for the <code>attrition</code> column, around 237 of all employees have left the company. This corresponds to a percentage of around 16% of all recorded employees. At the same time, 1233 employees have been staying with the company.</em></p>
<p><em>In addition, it might be interesting to plot the distribution of age faceted by the attrition value to see whether one can make any inferences from that relationship.</em></p>
<p><img src="/blogs/hw1_files/figure-html/facet_age_dist_by_attrition-1.png" width="960" style="display: block; margin: auto;" /></p>
<p><em>Looking at the two density plots, it is observable that values in the age variable tend to be lower for <code>Attrition</code> = Yes. One might speculate that younger employees tend to leave the company more often than older employees, because, on average, it is easier for them to find and adapt to a new job. Furthermore, as the analysis further below shows, compared to their older colleagues, they tend to have a lower salary, giving them less reason to stay with the company.</em></p>
<ul>
<li>How are <code>age</code>, <code>years_at_company</code>, <code>monthly_income</code> and <code>years_since_last_promotion</code> distributed? can you roughly guess which of these variables is closer to Normal just by looking at summary statistics?</li>
</ul>
<pre class="r"><code>n&lt;-length(hr_cleaned$age) 

pic_data&lt;-data.frame(cbind(c(hr_cleaned$age,hr_cleaned$monthly_income, 
                  hr_cleaned$years_since_last_promotion), 
                c(rep(&quot;age&quot;,n),rep(&quot;monthly_income&quot;,n),rep(&quot;years_since_last_promotion&quot;,n)))) 
colnames(pic_data)&lt;-c(&quot;Num&quot;,&quot;Attribute&quot;) 
pic_data$Num&lt;-as.integer(pic_data$Num) 

distribution&lt;-ggplot(pic_data, aes(x=Num))+ 
  geom_histogram()+ 
  facet_wrap(vars(Attribute), scale=&quot;free&quot;)+ 
  labs(title = &quot;Distribution across the dataset&quot;, subtitle = &quot;Counts of values for age, monthly income and years since last promotion&quot;, x=&quot;&quot;,y=&quot;Frequency&quot;)+ 
  
  theme_bw() 
distribution </code></pre>
<p><img src="/blogs/hw1_files/figure-html/age_years_income_promotion-1.png" width="960" style="display: block; margin: auto;" /></p>
<p><em>Looking at the three graphs, values for the age variable seem to be the most normally distributed, even though the distribution is skewed slightly to the right. This can be explained by the fact that the majority of the workforce lies in the age group 25-40. The remaining two graphs are skewed heavily to the right. The skewness of monthly income can be explained by the fact that most salaries tend to center around the mean, while there are large outliers on the higher side of income. Similarly, the distribution of <code>years_since_last_promotion</code> is in accordance with the frequency of employee promotion; people usually get promoted every 1-3 years.</em></p>
<ul>
<li>How are <code>job_satisfaction</code> and <code>work_life_balance</code> distributed? Don’t just report counts, but express categories as % of total.</li>
</ul>
<pre class="r"><code>hr_satis &lt;- hr_cleaned %&gt;% 
  group_by(job_satisfaction) %&gt;% 
  count(sort=TRUE) %&gt;% 
  rename(count=n)%&gt;%
  mutate(percent=count/1470)%&gt;%
  mutate(percent = percent(percent))


hr_satis </code></pre>
<pre><code>## # A tibble: 4 × 3
## # Groups:   job_satisfaction [4]
##   job_satisfaction count percent
##   &lt;chr&gt;            &lt;int&gt; &lt;chr&gt;  
## 1 Very High          459 31%    
## 2 High               442 30%    
## 3 Low                289 20%    
## 4 Medium             280 19%</code></pre>
<pre class="r"><code>work_life_satis &lt;- hr_cleaned %&gt;% 
  group_by(work_life_balance) %&gt;% 
  count(sort=TRUE) %&gt;% 
  rename(count=n)%&gt;%
  mutate(percent=count/1470)%&gt;%
  mutate(percent = percent(percent))
 
work_life_satis </code></pre>
<pre><code>## # A tibble: 4 × 3
## # Groups:   work_life_balance [4]
##   work_life_balance count percent
##   &lt;chr&gt;             &lt;int&gt; &lt;chr&gt;  
## 1 Better              893 61%    
## 2 Good                344 23%    
## 3 Best                153 10%    
## 4 Bad                  80 5%</code></pre>
<p><em>As for job satisfaction, 61% of employees reported that they are very highly or highly satisfied with their work while 19% of employees showed a low job satisfaction level. In general, job satisfaction levels seem to be evenly distributed throughout employees.</em></p>
<p><em>As for work-life balance,the majority (60%) of employees indicate that they have a better balance and only 5% think their work-life balance is bad.</em></p>
<ul>
<li>Is there any relationship between <code>monthly_income</code> and <code>education</code>? <code>monthly_income</code> and <code>gender</code>?</li>
</ul>
<pre class="r"><code>plot1 &lt;- ggplot(hr_cleaned, aes(x = fct_reorder(education, -monthly_income), y=monthly_income))+ #we include a negative &quot;-&quot; sign infront of monthly_income in the fct_reorder function, in order to sort the x axis based on decreasing y values
  geom_boxplot()+
  
  scale_y_continuous(labels = dollar)+
  
  labs(title = &quot;Education vs income&quot;, subtitle = &quot;A look at an employee&#39;s academic background and monthly income&quot;, x = &quot;Education&quot;, y = &quot;Monthly income&quot;)+
  
  theme_bw()
plot1 </code></pre>
<p><img src="/blogs/hw1_files/figure-html/income_education-1.png" width="960" style="display: block; margin: auto;" /></p>
<pre class="r"><code>plot2 &lt;-ggplot(hr_cleaned, aes(x = fct_reorder(gender, -monthly_income), y=monthly_income))+ 
  geom_boxplot()+
  
  scale_y_continuous(label = dollar)+
  
  labs(title = &quot;Gender vs income&quot;, subtitle = &quot;A look at an employee&#39;s sex and monthly income&quot;, x = &quot;Gender&quot;, y = &quot;Monthly income&quot;)+
  
  theme_bw()
plot2 </code></pre>
<p><img src="/blogs/hw1_files/figure-html/income_education-2.png" width="960" style="display: block; margin: auto;" /></p>
<p><em>The average monthly income seems to be based on the level of education. We can infer from the box plot that higher the education level, the higher the monthly income. There also exist a couple of outliers within the dataset - as some masters students tend to be paid higher than others. This could be relative for specific schools / universities and exceptional candidates that are paid highly for particular roles.</em></p>
<p><em>Interestingly, salaries don’t differ across genders as may be expected.</em></p>
<ul>
<li>Plot a boxplot of income vs job role. Make sure the highest-paid job roles appear first</li>
</ul>
<pre class="r"><code>income_vs_job &lt;- ggplot(hr_cleaned, aes(x=fct_reorder(job_role, -monthly_income), y=monthly_income)) + 
  geom_boxplot()+
  
  scale_y_continuous(labels = dollar)+
  
  labs(title = &quot;Income distribution by job&quot;, subtitle = &quot;A look at the relationship between job titles and monthly income&quot;, x = &quot;Job&quot; , y=&quot;Monthly income&quot;)+
  
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) #we adjust the labels on the x axis such that they are vertically aligned

  

income_vs_job</code></pre>
<p><img src="/blogs/hw1_files/figure-html/income_vs_job-1.png" width="960" style="display: block; margin: auto;" /></p>
<p><em>Across job roles, salaries differ significantly. For instance the monthly median salary for Managers is $17,500 while the one for Sales Representatives is just above $2,500. In addition, one can observe three salary groups: 1) around $2,700 2) around $7,000 and 3) around $17,000)</em></p>
<ul>
<li>Calculate and plot a bar chart of the mean (or median?) income by education level.</li>
</ul>
<pre class="r"><code>#We opted for plotting the MEDIAN monthly income, as it is typically less prone to outliers

median_income &lt;- hr_cleaned%&gt;%
  group_by(education)%&gt;%
  summarise(median_monthly_income = median(monthly_income))%&gt;%
  
  ggplot(aes(x = fct_reorder(education, -median_monthly_income), y = median_monthly_income))+
    geom_col(fill = &quot;lightblue&quot;)+
  
    scale_y_continuous(labels = dollar)+
  
    labs(title = &quot;Median income by education&quot;, subtitle = &quot;A look at the relationship between academic background and median monthly income&quot;, x = &quot;Education&quot; , y=&quot;Median monthly income&quot;)+
  
    theme_bw()

median_income</code></pre>
<p><img src="/blogs/hw1_files/figure-html/bar_income_edu-1.png" width="960" style="display: block; margin: auto;" /></p>
<p><em>The median salaries across education levels are aligned with the distribution of the salaries. PhDs have the highest median salary while employees without a college degree have the lowest median salary. Interestingly, the median salary for College graduates is slightly higher than the one for Bachelor graduates, given that the higher qualification is a Bachelors degree.</em></p>
<ul>
<li>Plot the distribution of income by education level. Use a facet_wrap and a theme from <code>ggthemes</code></li>
</ul>
<pre class="r"><code>plot7 &lt;- hr_cleaned %&gt;%  
  group_by(education) %&gt;%  
  ggplot(aes(x=monthly_income))+ 
    geom_histogram(fill = &quot;lightblue&quot;)+
    facet_wrap(vars(education), scales = &quot;free_y&quot;)+
  
    scale_x_continuous(labels = dollar)+
  
    labs(title = &quot;Income distribution by education&quot;, subtitle = &quot;A look at the relationship between edcuation level and monthly income&quot;, x = &quot;Monthly income&quot; , y=&quot;Count&quot;)+
  
    ggthemes::theme_stata()+
    theme(plot.background = element_blank()) #we remove the blue background to make the design more coherent
plot7 </code></pre>
<p><img src="/blogs/hw1_files/figure-html/dist_income_education-1.png" width="960" style="display: block; margin: auto;" /></p>
<p><em>Even though the total number of employees differs heavily across the educational backgrounds, the overall distribution stays similar. One can observe a reduction in counts of employees for salaries between $12,000 and $17,000. The frequency of employees tends to increase at the higher end of monthly income levels.</em></p>
<p><em>A similar picture is shown in the following density plot:</em></p>
<p><img src="/blogs/hw1_files/figure-html/density_plot-1.png" width="960" style="display: block; margin: auto;" /></p>
<ul>
<li>Plot income vs age, faceted by <code>job_role</code></li>
</ul>
<pre class="r"><code>plot8 &lt;- ggplot(hr_cleaned, aes(x=age, y=monthly_income))+ 
  geom_point(size=0.1)+ 
  geom_smooth(method = &quot;lm&quot;)+
  facet_wrap(vars(job_role), scales = &quot;free&quot;)+
  
  scale_y_continuous(labels = dollar)+
  
  labs(title = &quot;Income by age and job title&quot;, subtitle = &quot;A look at the relationship between age, job title and monthly income level&quot;, x = &quot;Age&quot; , y=&quot;Monthly income&quot;)+
  
  ggthemes::theme_stata()+
  theme(plot.background = element_blank())

plot8 </code></pre>
<p><img src="/blogs/hw1_files/figure-html/income_age_job-1.png" width="960" style="display: block; margin: auto;" /></p>
<p><em>The positive relationship between age and income stays consistent across job titles, i.e. the higher the age, the higher the monthly income. The strength of relationship, however, varies. For instance, the increase in salaries for research directors is higher than for research scientists.</em></p>
