---
categories:
- ""
- ""
date: "2017-10-31T22:26:09-06:00"
description: In this project,I mainly worked on worldbank data and investigated the correlation of GDP,fertility rate, life expectancy and education level in different countries worldwide.
draft: false
image: ""
keywords: ""
slug: hwtwo
title: Project 2 for Applied Statistics 
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<p>If we wanted to study climate change, we can find data on the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here</a>.</p>
<p>The period between 1951 - 1980 is our reference in defining temperature anomalies.</p>
<div id="loading-the-data-set" class="section level2">
<h2>Loading the data set</h2>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v4/NH.Ts+dSST.csv&quot;, 
           skip = 1,  #real data table only starts in Row 2, so we need to skip one row. 
           na = &quot;***&quot;) </code></pre>
<p>For each month and year, the data frame shows the deviation of temperature from the normal (expected).</p>
</div>
<div id="isolating-the-columns-we-need-and-tidy-data" class="section level2">
<h2>Isolating the columns we need and tidy data</h2>
<pre class="r"><code>tidyweather &lt;- weather %&gt;% 
  select(c(&quot;Year&quot;, &quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sep&quot;, &quot;Oct&quot;, &quot;Nov&quot;, &quot;Dec&quot;)) %&gt;%
  pivot_longer(cols=c(&#39;Jan&#39;, &#39;Feb&#39;, &#39;Mar&#39;, &#39;Apr&#39;, &#39;May&#39;, &#39;Jun&#39;, &#39;Jul&#39;, &#39;Aug&#39;, &#39;Sep&#39;, &#39;Oct&#39;, &#39;Nov&#39;, &#39;Dec&#39;),
               names_to = &quot;Month&quot;, values_to = &quot;Delta&quot;) </code></pre>
</div>
<div id="plotting-information" class="section level2">
<h2>Plotting information</h2>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         Month = month(date, label=TRUE),
         Year = year(date))</code></pre>
<pre class="r"><code>ggplot(tidyweather, aes(x=date, y=Delta))+
  geom_point(size = 0.5)+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies&quot;,
    subtitle = &quot;Temperature progression over time&quot;,
    x = &quot;Year&quot;,
    y = &quot;Delta in T (°C)&quot;
  )+
  # scale_x_date(date_breaks = seq(min(tidyweather$date), max(tidyweather$date), by = 8300))
     scale_x_date(date_labels = &quot;%Y&quot;, date_breaks = &quot;10 years&quot;)</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/graphDeltaWeather-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p>Scatter plot for each month:</p>
<pre class="r"><code>tidyweather$Month &lt;- factor(tidyweather$Month, 
                            levels = c(&quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sep&quot;, &quot;Oct&quot;, &quot;Nov&quot;, &quot;Dec&quot;)) #so that the facet wrap shows according to months

ggplot(tidyweather, aes(x=date, y=Delta))+
  geom_point(size = 0.3)+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  facet_wrap(vars(Month)) +
  labs (
     title = &quot;Weather Anomalies broken down by months&quot;,
    subtitle = &quot;Temperature progression over time&quot;,
    x = &quot;Year&quot;,
    y = &quot;Delta in T (°C)&quot;
  )</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/facet_wrap-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p><em>Based on our analysis, the effect of increasing temperature seems to be constant throughout the year. A more obvious indicator would be the Year instead - the effect of increasing temperature is more pronounced after the period between 1951-1980 as we can see a steep increase in the graph.</em></p>
</div>
<div id="grouping-the-data-into-time-periods" class="section level2">
<h2>Grouping the data into time periods</h2>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(Interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
</div>
<div id="distribution-of-monthly-deviations" class="section level2">
<h2>Distribution of monthly deviations</h2>
<pre class="r"><code>ggplot(comparison, aes(x=Delta, fill=Interval))+
  geom_density(alpha=0.2) +   #density plot with transparency set to 20%
  theme_bw() +                #theme
  labs (
    title = &quot;Density Plot for Monthly Temperature Anomalies&quot;,
    y     = &quot;Density&quot;,         #changing y-axis label to sentence case
    x = &quot;Delta in T (°C)&quot;
  )</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/density_plot-1.png" width="1056" style="display: block; margin: auto;" /></p>
</div>
<div id="average-annual-anomalies" class="section level2">
<h2>Average annual anomalies</h2>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   
  summarise(annual_average_delta = mean(Delta, na.rm=TRUE))

#plotting the data:
ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point(size = 0.8)+
  geom_smooth(colour = &quot;red&quot;) +
  theme_bw() +
labs (
     title = &quot;Average Yearly Temperature Anomaly&quot;,
    subtitle = &quot;Temperature progression over time&quot;,
    x = &quot;Year&quot;,
    y = &quot;Delta in T (°C)&quot;
  )+
  scale_x_continuous(n.breaks = 20)</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/averaging-1.png" width="1056" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<div id="confidence-interval-for-delta-formula" class="section level3">
<h3>Confidence Interval for <code>delta</code> (Formula)</h3>
<pre class="r"><code>formula_CI &lt;- comparison %&gt;% 
  filter(Interval == &quot;2011-present&quot;) %&gt;%
  summarize(median_delta = median(Delta, na.rm=TRUE),
            mean_delta = mean(Delta, na.rm=TRUE), 
            sd_delta = sd(Delta, na.rm=TRUE), 
            count = n(), 
            t_critical = qt(0.975, count -1),
            se_delta = sd_delta/sqrt(count), 
            margin_of_error = t_critical * se_delta,
            lower_CI_delta = mean_delta - margin_of_error,
            upper_CI_delta = mean_delta + margin_of_error
  )
            
#print out formula_CI
formula_CI</code></pre>
<pre><code>## # A tibble: 1 × 9
##   median_delta mean_delta sd_delta count t_critical se_delta margin_of_error
##          &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt;    &lt;dbl&gt;           &lt;dbl&gt;
## 1         1.04       1.06    0.274   132       1.98   0.0239          0.0473
## # … with 2 more variables: lower_CI_delta &lt;dbl&gt;, upper_CI_delta &lt;dbl&gt;</code></pre>
</div>
<div id="confidence-interval-for-delta-bootstrapping" class="section level3">
<h3>Confidence Interval for <code>delta</code> (Bootstrapping)</h3>
<pre class="r"><code>library(infer)

set.seed(1234)

boot_delta &lt;- comparison %&gt;% 
  filter(Interval == &quot;2011-present&quot;) %&gt;% 
  specify(response = Delta) %&gt;% 
  generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;% 
  calculate(stat=&quot;mean&quot;) 

percentile_ci &lt;- boot_delta %&gt;%  
  get_ci(level = 0.95, type = &quot;percentile&quot;)

#print out bootstrap_CI
percentile_ci</code></pre>
<pre><code>## # A tibble: 1 × 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.02     1.11</code></pre>
</div>
<div id="comparison-of-confidence-intervals" class="section level3">
<h3>Comparison of Confidence Intervals</h3>
<pre class="r"><code>visualize(boot_delta) +
  shade_ci(endpoints = percentile_ci) + 
  geom_vline(xintercept = formula_CI$lower_CI_delta, linetype = &quot;dashed&quot;, colour = &quot;red&quot;, size = 1) +
  geom_vline(xintercept = formula_CI$upper_CI_delta,linetype = &quot;dashed&quot;, colour = &quot;red&quot;, size = 1) + 
  theme_bw() +
  labs(
    title = &quot;Bootstrap CI for Average Annual Delta since 2011&quot;, 
    subtitle = &quot;Fomula CI shown with dashed red lines&quot;,
    x = &quot;Delta T (°C)&quot;,
    y = &quot;Count&quot;
    
  )</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/visualizing_bootstrap-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p><em>Based on our analysis, the 95% confidence interval (CI) for the average annual delta since 2011 was calculated as (1.01, 1.11). This means that we can be 95% confident that the average annual delta falls within 1.01 and 1.11. We constructed the CI using the formula method and using a bootstrap simulation, both method gives us a very similar width - the shaded area is the CI calculated using a bootstrap simulation and the range between the dotted lines is the CI calculated using the formula.</em></p>
</div>
</div>
</div>
<div id="general-social-survey-gss" class="section level1">
<h1>General Social Survey (GSS)</h1>
<p>The <a href="http://www.gss.norc.org/">General Social Survey (GSS)</a> gathers data on American society in order to monitor and explain trends in attitudes, behaviours, and attributes. Many trends have been tracked for decades, so one can see the evolution of attitudes, etc in American Society.remove.packages(“affycoretools”)</p>
<p>In this assignment we analyze data from the <strong>2016 GSS sample data</strong>, using it to estimate values of <em>population parameters</em> of interest about US adults. The GSS sample data file has 2867 observations of 935 variables, but we are only interested in very few of these variables and you are using a smaller file.</p>
<pre class="r"><code>gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,
                       &quot;No answer&quot;, &quot;Not applicable&quot;))</code></pre>
<p>The variables we have are the following:</p>
<ul>
<li>hours and minutes spent on email weekly. The responses to these questions are recorded in the <code>emailhr</code> and <code>emailmin</code> variables. For example, if the response is 2.50 hours, this would be recorded as emailhr = 2 and emailmin = 30.</li>
<li><code>snapchat</code>, <code>instagrm</code>, <code>twitter</code>: whether respondents used these social media in 2016</li>
<li><code>sex</code>: Female - Male</li>
<li><code>degree</code>: highest education level attained</li>
</ul>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>Instagram and Snapchat, by sex</h2>
<p>Can we estimate the <em>population</em> proportion of Snapchat or Instagram users in 2016?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable, <code>snap_insta</code> that is <em>Yes</em> if the respondent reported using any of Snapchat (<code>snapchat</code>) or Instagram (<code>instagrm</code>), and <em>No</em> if not. If the recorded value was NA for both of these questions, the value in your new variable should also be NA.</li>
</ol>
<pre class="r"><code>gss_snap_insta &lt;- gss %&gt;% 
mutate(snap_insta = case_when( 
      snapchat == &quot;Yes&quot; ~ &quot;Yes&quot;, 
      instagrm == &quot;Yes&quot; ~ &quot;Yes&quot;, 
      snapchat == &quot;No&quot; ~ &quot;No&quot;, 
      instagrm == &quot;No&quot; ~ &quot;No&quot;
      )) 
gss_snap_insta</code></pre>
<pre><code>## # A tibble: 2,867 × 8
##    emailmin emailhr snapchat instagrm twitter sex    degree         snap_insta
##    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;          &lt;chr&gt;     
##  1 0        12      NA       NA       NA      Male   Bachelor       &lt;NA&gt;      
##  2 30       0       No       No       No      Male   High school    No        
##  3 NA       NA      No       No       No      Male   Bachelor       No        
##  4 10       0       NA       NA       NA      Female High school    &lt;NA&gt;      
##  5 NA       NA      Yes      Yes      No      Female Graduate       Yes       
##  6 0        2       No       Yes      No      Female Junior college Yes       
##  7 0        40      NA       NA       NA      Male   High school    &lt;NA&gt;      
##  8 NA       NA      Yes      Yes      No      Female High school    Yes       
##  9 0        0       NA       NA       NA      Male   High school    &lt;NA&gt;      
## 10 NA       NA      No       No       No      Male   Junior college No        
## # … with 2,857 more rows</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Calculate the proportion of Yes’s for <code>snap_insta</code> among those who answered the question, i.e. excluding NAs.</li>
</ol>
<pre class="r"><code>gss_proportion &lt;- gss_snap_insta %&gt;%
  group_by(snap_insta)%&gt;% 
  summarise(n = sum(!is.na(snap_insta)))%&gt;% #count people that use or don&#39;t use either snapchat of instagram excluding NA
  mutate(Prop_prct = n/sum(n)*100) # divide each veriable of &quot;No&quot; and &quot;Yes&quot; by total to get proportion
gss_proportion </code></pre>
<pre><code>## # A tibble: 3 × 3
##   snap_insta     n Prop_prct
##   &lt;chr&gt;      &lt;int&gt;     &lt;dbl&gt;
## 1 No           858      62.5
## 2 Yes          514      37.5
## 3 &lt;NA&gt;           0       0</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Using the CI formula for proportions, please construct 95% CIs for men and women who used either Snapchat or Instagram</li>
</ol>
<pre class="r"><code>count_sex_snap_insta &lt;- gss_snap_insta%&gt;%
  count(sex, snap_insta)%&gt;% 
  na.omit() # omit NA rows
count_sex_snap_insta</code></pre>
<pre><code>## # A tibble: 4 × 3
##   sex    snap_insta     n
##   &lt;chr&gt;  &lt;chr&gt;      &lt;int&gt;
## 1 Female No           447
## 2 Female Yes          322
## 3 Male   No           411
## 4 Male   Yes          192</code></pre>
<pre class="r"><code>CI_male_test &lt;-  prop.test(as.double(count_sex_snap_insta[4,&quot;n&quot;]), as.double(count_sex_snap_insta[4,&quot;n&quot;])+as.double(count_sex_snap_insta[3,&quot;n&quot;])) # Construct test to obtain 95% CI for men who used either Snapchat or Instragram
CI_female_test &lt;-  prop.test(as.double(count_sex_snap_insta[2, &quot;n&quot;]),as.double(count_sex_snap_insta[2, &quot;n&quot;])+as.double(count_sex_snap_insta[1, &quot;n&quot;]) ) # Construct test to obtain 95% CI for women who used either Snapchat or Instragram

CI_male_test</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  as.double out of +count_sex_snap_insta[4, &quot;n&quot;] out of as.double(count_sex_snap_insta[4, &quot;n&quot;])as.double out of as.double(count_sex_snap_insta[3, &quot;n&quot;])
## X-squared = 79, df = 1, p-value &lt;2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.282 0.357
## sample estimates:
##     p 
## 0.318</code></pre>
<pre class="r"><code>CI_female_test</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  as.double out of +count_sex_snap_insta[2, &quot;n&quot;] out of as.double(count_sex_snap_insta[2, &quot;n&quot;])as.double out of as.double(count_sex_snap_insta[1, &quot;n&quot;])
## X-squared = 20, df = 1, p-value = 8e-06
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.384 0.455
## sample estimates:
##     p 
## 0.419</code></pre>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>Twitter, by education level</h2>
<p>Can we estimate the <em>population</em> proportion of Twitter users by education level in 2016?.</p>
<p>There are 5 education levels in variable <code>degree</code> which, in ascending order of years of education, are Lt high school, High School, Junior college, Bachelor, Graduate.</p>
<ol style="list-style-type: decimal">
<li>Turn <code>degree</code> from a character variable into a factor variable. Make sure the order is the correct one and that levels are not sorted alphabetically which is what R by default does.</li>
</ol>
<pre class="r"><code>gss_factor &lt;- gss%&gt;%
  mutate(degree = as.factor(degree))%&gt;%
  arrange(match(degree, c(&quot;Lt high school&quot;, &quot;High School&quot;, &quot;Junior College&quot;, &quot;Bachelor&quot;, &quot;Graduate&quot;)), desc(degree)) # Manually specify order using arrange and match
gss_factor</code></pre>
<pre><code>## # A tibble: 2,867 × 7
##    emailmin emailhr snapchat instagrm twitter sex    degree        
##    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;fct&gt;         
##  1 30       0       No       No       No      Male   Lt high school
##  2 0        1       NA       NA       NA      Female Lt high school
##  3 NA       NA      No       Yes      No      Female Lt high school
##  4 0        1       Yes      Yes      No      Female Lt high school
##  5 NA       NA      NA       NA       NA      Female Lt high school
##  6 45       0       NA       NA       NA      Female Lt high school
##  7 NA       NA      No       Yes      No      Male   Lt high school
##  8 20       0       NA       NA       NA      Female Lt high school
##  9 NA       NA      NA       NA       NA      Female Lt high school
## 10 NA       NA      NA       NA       NA      Female Lt high school
## # … with 2,857 more rows</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Create a new variable, <code>bachelor_graduate</code> that is <em>Yes</em> if the respondent has either a <code>Bachelor</code> or <code>Graduate</code> degree. As before, if the recorded value for either was NA, the value in your new variable should also be NA.</li>
</ol>
<pre class="r"><code>gss_bachelor_graduate &lt;- gss%&gt;%
mutate(bachelor_graduate = case_when(
  degree == &quot;Bachelor&quot; ~ &quot;Yes&quot;,
  degree == &quot;Graduate&quot; ~ &quot;Yes&quot;
      ))

gss_bachelor_graduate</code></pre>
<pre><code>## # A tibble: 2,867 × 8
##    emailmin emailhr snapchat instagrm twitter sex    degree         bachelor_gradua…
##    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;          &lt;chr&gt;           
##  1 0        12      NA       NA       NA      Male   Bachelor       Yes             
##  2 30       0       No       No       No      Male   High school    &lt;NA&gt;            
##  3 NA       NA      No       No       No      Male   Bachelor       Yes             
##  4 10       0       NA       NA       NA      Female High school    &lt;NA&gt;            
##  5 NA       NA      Yes      Yes      No      Female Graduate       Yes             
##  6 0        2       No       Yes      No      Female Junior college &lt;NA&gt;            
##  7 0        40      NA       NA       NA      Male   High school    &lt;NA&gt;            
##  8 NA       NA      Yes      Yes      No      Female High school    &lt;NA&gt;            
##  9 0        0       NA       NA       NA      Male   High school    &lt;NA&gt;            
## 10 NA       NA      No       No       No      Male   Junior college &lt;NA&gt;            
## # … with 2,857 more rows</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Calculate the proportion of <code>bachelor_graduate</code> who do (Yes) and who don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>gss_proportion_twr &lt;- gss_bachelor_graduate%&gt;%
  group_by(bachelor_graduate, twitter)%&gt;%
  na.omit()%&gt;% # Exlude NA rows
  filter(twitter!=&quot;NA&quot;)%&gt;%  # Exclude rows with character &quot;NA&quot;
  summarise(n = count(twitter))%&gt;% #count people that use twitter
  mutate(prop_twitter_prct = n/sum(n)*100) # divide each variable of bachelor and graduate students who use or don&#39;t use twitter by total to get proportion
gss_proportion_twr </code></pre>
<pre><code>## # A tibble: 2 × 4
## # Groups:   bachelor_graduate [1]
##   bachelor_graduate twitter     n prop_twitter_prct
##   &lt;chr&gt;             &lt;chr&gt;   &lt;int&gt;             &lt;dbl&gt;
## 1 Yes               No        375              76.7
## 2 Yes               Yes       114              23.3</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Using the CI formula for proportions, please construct two 95% CIs for <code>bachelor_graduate</code> vs whether they use (Yes) and don’t (No) use twitter.</li>
</ol>
<pre class="r"><code>CI_no_twitter_test &lt;-  prop.test(as.double(gss_proportion_twr[1,&quot;n&quot;]), as.double(count_sex_snap_insta[2,&quot;n&quot;])+as.double(count_sex_snap_insta[1,&quot;n&quot;])) # Construct test to obtain 95% CI for bachelor and graduate students who do not use twitter
CI_yes_twitter_test &lt;-  prop.test(as.double(gss_proportion_twr[2,&quot;n&quot;]), as.double(count_sex_snap_insta[2,&quot;n&quot;])+as.double(count_sex_snap_insta[1,&quot;n&quot;])) # Construct test to obtain 95% CI for bachelor and graduate students who use twitter


CI_no_twitter_test</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  as.double out of +gss_proportion_twr[1, &quot;n&quot;] out of as.double(count_sex_snap_insta[2, &quot;n&quot;])as.double out of as.double(count_sex_snap_insta[1, &quot;n&quot;])
## X-squared = 0.4, df = 1, p-value = 0.5
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.452 0.524
## sample estimates:
##     p 
## 0.488</code></pre>
<pre class="r"><code>CI_yes_twitter_test</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  as.double out of +gss_proportion_twr[2, &quot;n&quot;] out of as.double(count_sex_snap_insta[2, &quot;n&quot;])as.double out of as.double(count_sex_snap_insta[1, &quot;n&quot;])
## X-squared = 379, df = 1, p-value &lt;2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.124 0.176
## sample estimates:
##     p 
## 0.148</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>Do these two Confidence Intervals overlap?</li>
</ol>
<p><em>The two confidence intervals do not overlap. The 95% CI for bachelor and graduates who use twitter is</em> <span class="math display">\[0.124, 0.176\]</span><em>, while the one for those who do not use twitter is <span class="math display">\[0.452, 0.524\]</span>, hence there is a difference of 0.276 between both.</em></p>
</div>
<div id="email-usage" class="section level2">
<h2>Email usage</h2>
<p>Can we estimate the <em>population</em> parameter on time spent on email weekly?</p>
<ol style="list-style-type: decimal">
<li>Create a new variable called <code>email</code> that combines <code>emailhr</code> and <code>emailmin</code> to report the number of minutes the respondents spend on email weekly.</li>
</ol>
<pre class="r"><code>gss_email &lt;- gss%&gt;%
  filter(emailhr!=&quot;NA&quot;, emailmin!=&quot;NA&quot;, degree!=&quot;NA&quot;)%&gt;% # Exclude rows containing character &quot;NA&quot;
  mutate(emailhr = as.double(emailhr) * 60)%&gt;% # Obtain hours in minutes and as a double
  mutate(emailmin = as.double(emailmin))%&gt;% # Change minutes to double
  rowwise()%&gt;%
  mutate(email = sum(emailmin, emailhr)) # Sum hours and minutes spent on email a week and create new column email with the sum

gss_email</code></pre>
<pre><code>## # A tibble: 1,648 × 8
## # Rowwise: 
##    emailmin emailhr snapchat instagrm twitter sex    degree         email
##       &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;          &lt;dbl&gt;
##  1        0     720 NA       NA       NA      Male   Bachelor         720
##  2       30       0 No       No       No      Male   High school       30
##  3       10       0 NA       NA       NA      Female High school       10
##  4        0     120 No       Yes      No      Female Junior college   120
##  5        0    2400 NA       NA       NA      Male   High school     2400
##  6        0       0 NA       NA       NA      Male   High school        0
##  7        0     120 No       No       No      Female High school      120
##  8        0     600 No       No       No      Male   High school      600
##  9       30       0 No       No       No      Male   Lt high school    30
## 10        0      60 NA       NA       NA      Female Lt high school    60
## # … with 1,638 more rows</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Visualise the distribution of this new variable. Find the mean and the median number of minutes respondents spend on email weekly. Is the mean or the median a better measure of the typical amount of time Americans spend on email weekly? Why?</li>
</ol>
<p><em>The median <code>dashed orange line</code> is more representative of the typical amount of time Americans spend on email weekly than the mean <code>dashed red line</code>. This is mostly due to the fact that the distribution is heavily right skewed, meaning that there are few Americans who spend a long time on email and most remain within the 0-500 minutes a week. As it can be observed from the mean and median table, for all degree groups, mean gives higher values resulting from a few Americans spending a lot of time on emails, making the mean less representative than the median.</em></p>
<pre class="r"><code>email_distribution &lt;- ggplot(gss_email, aes(x = email))+
  geom_histogram(bins = 35)+
  geom_vline(aes(xintercept = median(email)), linetype = &quot;dashed&quot;, colour = &quot;orange&quot;, size = 0.5)+ # create orange dashed line displaying median value
  geom_vline(aes(xintercept = mean(email)), linetype = &quot;dashed&quot;, colour = &quot;red&quot;, size = 0.5)+ # create red dashed line displaying mean value

  facet_wrap(vars(degree), scale = &quot;free&quot;)+ # facet wrap by degree
  ggthemes::theme_stata()+
  theme(plot.background = element_blank())

  
email_distribution</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/face_wrap_email-1.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>email_mean &lt;- gss_email%&gt;%
  group_by(degree)%&gt;%
  summarise(mean = mean(email), median = median(email))%&gt;%
  arrange(match(degree, c(&quot;Lt high school&quot;, &quot;High School&quot;, &quot;Junior College&quot;, &quot;Bachelor&quot;, &quot;Graduate&quot;)), desc(degree)) # create dataframe showing mean and median values for each education level
email_mean</code></pre>
<pre><code>## # A tibble: 5 × 3
##   degree          mean median
##   &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt;
## 1 Lt high school  198.     20
## 2 Bachelor        573.    240
## 3 Graduate        601.    300
## 4 Junior college  380.    120
## 5 High school     352.    120</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>Using the <code>infer</code> package, calculate a 95% bootstrap confidence interval for the mean amount of time Americans spend on email weekly. Interpret this interval in context of the data, reporting its endpoints in “humanized” units (e.g. instead of 108 minutes, report 1 hr and 8 minutes). If you get a result that seems a bit odd, discuss why you think this might be the case.</li>
</ol>
<pre class="r"><code>boot_emails &lt;- email_mean%&gt;%
  specify(response = mean)%&gt;% # Specify variable of interest - mean of time spent on email weekly
  generate(reps = 1000, type = &quot;bootstrap&quot;)%&gt;% # Generate 1000 bootstrap samples
  calculate(stat = &quot;mean&quot;) # find mean of each sample

percentile_ci &lt;- boot_emails%&gt;%
  get_confidence_interval(level = 0.95, type = &quot;percentile&quot;)%&gt;% # obtain CI
  mutate(lower_ci = round_hms(as.hms(lower_ci*60),1), upper_ci = round_hms(as.hms(upper_ci*60),1)) %&gt;% # convert values into readable time format
  rename(&quot;Lower CI h:m:s&quot;= lower_ci, &quot;Upper CI h:m:s&quot; = upper_ci)

percentile_ci</code></pre>
<pre><code>## # A tibble: 1 × 2
##   `Lower CI h:m:s` `Upper CI h:m:s`
##   &lt;time&gt;           &lt;time&gt;          
## 1 04:56:20         09:05:38</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Would you expect a 99% confidence interval to be wider or narrower than the interval you calculated above? Explain your reasoning.</li>
</ol>
<p><em>The interval for the mean value of hours spend on email a week would be wider because the t-critical value would increase, given that the confidence level rises to 99%.</em></p>
</div>
</div>
<div id="bidens-approval-margins" class="section level1">
<h1>Biden’s Approval Margins</h1>
<p>As we saw in class, fivethirtyeight.com has detailed data on <a href="https://projects.fivethirtyeight.com/biden-approval-ratings">all polls that track the president’s approval</a></p>
<pre class="r"><code># Import approval polls data directly off fivethirtyeight website
approval_polllist &lt;- read_csv(&#39;https://projects.fivethirtyeight.com/biden-approval-data/approval_polllist.csv&#39;) 

glimpse(approval_polllist)</code></pre>
<pre><code>## Rows: 1,600
## Columns: 22
## $ president           &lt;chr&gt; &quot;Joseph R. Biden Jr.&quot;, &quot;Joseph R. Biden Jr.&quot;, &quot;Jos…
## $ subgroup            &lt;chr&gt; &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;, &quot;All polls&quot;…
## $ modeldate           &lt;chr&gt; &quot;9/17/2021&quot;, &quot;9/17/2021&quot;, &quot;9/17/2021&quot;, &quot;9/17/2021&quot;…
## $ startdate           &lt;chr&gt; &quot;1/31/2021&quot;, &quot;2/1/2021&quot;, &quot;2/1/2021&quot;, &quot;2/2/2021&quot;, &quot;…
## $ enddate             &lt;chr&gt; &quot;2/2/2021&quot;, &quot;2/3/2021&quot;, &quot;2/3/2021&quot;, &quot;2/4/2021&quot;, &quot;2…
## $ pollster            &lt;chr&gt; &quot;YouGov&quot;, &quot;Rasmussen Reports/Pulse Opinion Researc…
## $ grade               &lt;chr&gt; &quot;B+&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;A-&quot;, &quot;B&quot;, &quot;B-&quot;, &quot;…
## $ samplesize          &lt;dbl&gt; 1500, 1500, 15000, 1500, 15000, 1005, 1429, 15000,…
## $ population          &lt;chr&gt; &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;lv&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;a&quot;, &quot;rv&quot;, &quot;l…
## $ weight              &lt;dbl&gt; 1.0856, 0.3308, 0.2786, 0.3086, 0.2507, 0.8741, 2.…
## $ influence           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
## $ approve             &lt;dbl&gt; 46, 52, 54, 49, 54, 57, 49, 54, 60, 50, 54, 55, 51…
## $ disapprove          &lt;dbl&gt; 38, 46, 33, 48, 34, 34, 39, 34, 32, 47, 34, 33, 46…
## $ adjusted_approve    &lt;dbl&gt; 47.2, 54.4, 52.5, 51.4, 52.5, 55.9, 49.6, 52.5, 59…
## $ adjusted_disapprove &lt;dbl&gt; 38.3, 40.1, 36.3, 42.1, 37.3, 35.1, 39.1, 37.3, 33…
## $ multiversions       &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ tracking            &lt;lgl&gt; NA, TRUE, TRUE, TRUE, TRUE, NA, NA, TRUE, NA, TRUE…
## $ url                 &lt;chr&gt; &quot;https://docs.cdn.yougov.com/460mactkmh/econTabRep…
## $ poll_id             &lt;dbl&gt; 74332, 74338, 74366, 74347, 74367, 74345, 74348, 7…
## $ question_id         &lt;dbl&gt; 139593, 139642, 139733, 139654, 139734, 139652, 13…
## $ createddate         &lt;chr&gt; &quot;2/3/2021&quot;, &quot;2/4/2021&quot;, &quot;2/11/2021&quot;, &quot;2/5/2021&quot;, &quot;…
## $ timestamp           &lt;chr&gt; &quot;13:01:54 17 Sep 2021&quot;, &quot;13:01:54 17 Sep 2021&quot;, &quot;1…</code></pre>
<pre class="r"><code># Use `lubridate` to fix dates, as they are given as characters.</code></pre>
<div id="create-a-plot" class="section level2">
<h2>Create a plot</h2>
<pre class="r"><code>approval_polllist$enddate&lt;-mdy(approval_polllist$enddate)

approval_plot&lt;-approval_polllist%&gt;%
  filter(subgroup==&quot;Voters&quot;)%&gt;% #limit the data to group &quot;Voters&quot; in order to recreate the graph
  select(enddate,pollster,samplesize,weight,approve, disapprove)%&gt;%
  mutate(week_poll=week(enddate),mg_approval=approve-disapprove) #obtain the week of the enddate, to plot it against average approval

approval_biden&lt;-approval_plot%&gt;% 
 group_by(week_poll)%&gt;%
  summarise(margin_apr_mean=mean(mg_approval),
            sd_margin=sd(mg_approval),
            count_pollster=n(),
            t_critical = qt(0.975,count_pollster-1), #calculate t critical, for 95% confidence (2.5% per side)
            se_margin=sd_margin/sqrt(count_pollster),
            lower_interval=margin_apr_mean-t_critical*se_margin,
            higher_interval=margin_apr_mean+t_critical*se_margin, #calculate confidence interval
            )</code></pre>
<pre class="r"><code>approval_plot1&lt;-ggplot(approval_biden,aes(x=week_poll))+
  geom_line(aes(y=margin_apr_mean),color=&quot;red&quot;,size=0.5)+
  geom_point(aes(y=margin_apr_mean),color=&quot;red&quot;,size=0.8)+
  geom_smooth(aes(y=margin_apr_mean),se=FALSE,size=0.8)+
  geom_line(aes(y=lower_interval),color=&quot;pink&quot;,size=0.3)+
  geom_line(aes(y=higher_interval),color=&quot;pink&quot;,size=0.3)+
  geom_ribbon(aes(ymin=higher_interval,ymax=lower_interval),fill=&quot;grey&quot;,alpha=0.3)+
  geom_hline(yintercept =0,color=&quot;orange&quot;,size=1)+
  
  labs(x=&quot;Week of the year&quot;,y=&quot;Average approval margin (approval - disapproval)&quot;,
       title = &quot;Estimating approval margin(approval - disapproval) for Biden&quot;,
       subtitle = &quot;2021 weekly average of all polls&quot;)+
  
  theme_bw()+
  theme(plot.background = element_rect(fill = NA , colour = &#39;grey&#39;,size=0.1))+
  theme(panel.border = element_rect(colour = NA, fill=NA))+
  ylim(-15,30)
     
approval_plot1</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/biden_plot-1.png" width="1056" style="display: block; margin: auto;" /></p>
</div>
<div id="compare-confidence-intervals" class="section level2">
<h2>Compare Confidence Intervals</h2>
<p>Compare the confidence intervals for <code>week 4</code> and <code>week 25</code>. Can you explain what’s going on? One paragraph would be enough.</p>
<p><em>The large confidence interval from week 4 very likely ascribes to the small sample of that week, while week 25 has a comparatively large sample size and hence a much smaller confidence interval.</em></p>
</div>
</div>
<div id="gapminder-revisited" class="section level1">
<h1>Gapminder revisited</h1>
<p>Recall the <code>gapminder</code> data frame from the gapminder package.</p>
<ul>
<li>Life expectancy at birth (life_expectancy_years.csv)</li>
<li>GDP per capita in constant 2010 US$ (<a href="https://data.worldbank.org/indicator/NY.GDP.PCAP.KD" class="uri">https://data.worldbank.org/indicator/NY.GDP.PCAP.KD</a>)</li>
<li>Female fertility: The number of babies per woman (<a href="https://data.worldbank.org/indicator/SP.DYN.TFRT.IN" class="uri">https://data.worldbank.org/indicator/SP.DYN.TFRT.IN</a>)</li>
<li>Primary school enrollment as % of children attending primary school (<a href="https://data.worldbank.org/indicator/SE.PRM.NENR" class="uri">https://data.worldbank.org/indicator/SE.PRM.NENR</a>)</li>
<li>Mortality rate, for under 5, per 1000 live births (<a href="https://data.worldbank.org/indicator/SH.DYN.MORT" class="uri">https://data.worldbank.org/indicator/SH.DYN.MORT</a>)</li>
<li>HIV prevalence (adults_with_hiv_percent_age_15_49.csv): The estimated number of people living with HIV per 100 population of age group 15-49.</li>
</ul>
<pre class="r"><code># load gapminder HIV data
hiv &lt;- read_csv(here::here(&quot;data&quot;,&quot;adults_with_hiv_percent_age_15_49.csv&quot;))
life_expectancy &lt;- read_csv(here::here(&quot;data&quot;,&quot;life_expectancy_years.csv&quot;))

# get World bank data using wbstats
indicators &lt;- c(&quot;SP.DYN.TFRT.IN&quot;,&quot;SE.PRM.NENR&quot;, &quot;SH.DYN.MORT&quot;, &quot;NY.GDP.PCAP.KD&quot;)


library(wbstats)

worldbank_data &lt;- wb_data(country=&quot;countries_only&quot;, #countries only- no aggregates like Latin America, Europe, etc.
                          indicator = indicators, 
                          start_date = 1960, 
                          end_date = 2016)

# get a dataframe of information regarding countries, indicators, sources, regions, indicator topics, lending types, income levels,  from the World Bank API 
countries &lt;-  wbstats::wb_cachelist$countries</code></pre>
<pre class="r"><code>#hiv prevalence into year
hiv_1 &lt;- hiv %&gt;% 
  pivot_longer(cols=2:34, 
               names_to=&quot;year&quot;, 
               values_to = &quot;hiv_pct&quot;)

#life expectancy
life_exp1 &lt;- life_expectancy %&gt;% 
    pivot_longer(cols=2:302, 
               names_to=&quot;year&quot;, 
               values_to = &quot;life_expectancy&quot;)
 
colnames(worldbank_data)[4] &lt;- &quot;year&quot;</code></pre>
<pre class="r"><code>#join df together,because hiv data contains data from 1979-2011 while life expectancy data is from 1800-2100, so left join will guarantee there will be less NULL data
new_dataset &lt;- hiv_1 %&gt;% 
  left_join(life_exp1, by=c(&quot;country&quot;,&quot;year&quot;))
#change data type
new_dataset &lt;- new_dataset %&gt;%
 mutate(year=as.numeric(year)) 

new_dataset &lt;- new_dataset %&gt;% 
  left_join(worldbank_data, by=c(&quot;country&quot;,&quot;year&quot;))

#only keep the necessary columns to make the dataset smaller
country &lt;- countries %&gt;%
  select(country,region,region_iso3c,region_iso2c)

new_dataset&lt;- new_dataset  %&gt;% 
  left_join(country, by=c(&quot;country&quot;))

## remove those countries that don&#39;t have a region
new_dataset&lt;- subset(new_dataset,region!=&quot;NA&quot;)

skim(new_dataset)</code></pre>
<table>
<caption>(#tab:join the df)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">new_dataset</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">4719</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">6</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">7</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">country</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">24</td>
<td align="right">0</td>
<td align="right">143</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">iso2c</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">143</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">iso3c</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">143</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">region</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">10</td>
<td align="right">26</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">region_iso3c</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">region_iso2c</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="15%" />
<col width="9%" />
<col width="13%" />
<col width="8%" />
<col width="8%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="8%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">year</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">1995.00</td>
<td align="right">9.52</td>
<td align="right">1979.00</td>
<td align="right">1987.00</td>
<td align="right">1995.00</td>
<td align="right">2003.0</td>
<td align="right">2.01e+03</td>
<td align="left">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td align="left">hiv_pct</td>
<td align="right">1602</td>
<td align="right">0.66</td>
<td align="right">1.68</td>
<td align="right">3.89</td>
<td align="right">0.01</td>
<td align="right">0.10</td>
<td align="right">0.30</td>
<td align="right">1.2</td>
<td align="right">2.65e+01</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">life_expectancy</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">66.27</td>
<td align="right">9.87</td>
<td align="right">9.64</td>
<td align="right">58.00</td>
<td align="right">68.90</td>
<td align="right">74.3</td>
<td align="right">8.34e+01</td>
<td align="left">▁▁▂▆▇</td>
</tr>
<tr class="even">
<td align="left">NY.GDP.PCAP.KD</td>
<td align="right">562</td>
<td align="right">0.88</td>
<td align="right">10316.40</td>
<td align="right">16119.03</td>
<td align="right">164.34</td>
<td align="right">1001.85</td>
<td align="right">3137.34</td>
<td align="right">10320.6</td>
<td align="right">1.12e+05</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">SE.PRM.NENR</td>
<td align="right">2397</td>
<td align="right">0.49</td>
<td align="right">83.81</td>
<td align="right">18.71</td>
<td align="right">13.52</td>
<td align="right">79.52</td>
<td align="right">91.57</td>
<td align="right">96.4</td>
<td align="right">1.00e+02</td>
<td align="left">▁▁▁▁▇</td>
</tr>
<tr class="even">
<td align="left">SH.DYN.MORT</td>
<td align="right">36</td>
<td align="right">0.99</td>
<td align="right">71.17</td>
<td align="right">68.61</td>
<td align="right">2.50</td>
<td align="right">14.70</td>
<td align="right">45.40</td>
<td align="right">111.7</td>
<td align="right">3.37e+02</td>
<td align="left">▇▃▂▁▁</td>
</tr>
<tr class="odd">
<td align="left">SP.DYN.TFRT.IN</td>
<td align="right">17</td>
<td align="right">1.00</td>
<td align="right">3.71</td>
<td align="right">1.96</td>
<td align="right">1.08</td>
<td align="right">1.91</td>
<td align="right">3.13</td>
<td align="right">5.5</td>
<td align="right">8.46e+00</td>
<td align="left">▇▅▃▃▁</td>
</tr>
</tbody>
</table>
<pre class="r"><code>#join again to get data from 1960--2016（the data in newdataset is 1979-2011)
worldbank2&lt;- worldbank_data %&gt;%
  left_join(country, by=c(&quot;country&quot;))
worldbank2&lt;- subset(worldbank2,region!=&quot;NA&quot;)</code></pre>
<ol style="list-style-type: decimal">
<li>What is the relationship between HIV prevalence and life expectancy? Generate a scatterplot with a smoothing line to report your results. You may find faceting useful</li>
</ol>
<pre class="r"><code>#overall condition
hiv_life_expectancy &lt;- ggplot(new_dataset,aes(x=hiv_pct, y=life_expectancy))+
  geom_point(aes(color=region), size=0.2)+
  ylim(30,90)+
  theme_bw()+
  geom_smooth(method = &quot;lm&quot;)+
  labs(title = &quot;Scatterplot of HIV prevalence and life expectancy&quot;, y = &quot;life expectancy&quot;, x= &quot;HIV prevalence %&quot;)+
 # theme(legend.position = &quot;none&quot;)+
  NULL

hiv_life_expectancy</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/hiv_life_expectancy-1.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#faceting by regions
hiv_life_expectancy_region &lt;- ggplot(new_dataset, aes(x=hiv_pct, y=life_expectancy))+
  geom_point(aes(color=region), size=0.2)+
  geom_smooth(method = &quot;lm&quot;)+
  labs(title = &quot;HIV prevalence and life expectancy by region&quot;, y = &quot;Life expectancy &quot;, x= &quot;HIV prevalence %&quot;, subtitle = &quot;Scatterplots seperated by regions&quot;)+
 # xlim(0,3)+
  ylim(30,90)+
  theme_bw()+
  facet_wrap(vars(region), scales = &quot;free&quot; )+
  theme(legend.position = &quot;none&quot;)+
  NULL

hiv_life_expectancy_region</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/hiv_life_expectancy-2.png" width="1056" style="display: block; margin: auto;" />
<em>From the scatterplot above, we can observe that HIV prevalence is generally negatively related with life expectancy. Those countries with higher life expectancy are more likely to have lower HIV prevalence rates, probably because those countries are in better medical conditions. As for the difference between regions, most regions show a negative relationship between HIV prevalence and life expectancy, except Europe&amp; Central Asia and North America. This is probably because these regions keep very low HIV prevalence so the pattern is not so obvious. Another point is that Sub-Saharan Africa has a lower life expectancy and higher HIV prevalence compared to other regions.</em></p>
<ol start="2" style="list-style-type: decimal">
<li>What is the relationship between fertility rate and GDP per capita? Generate a scatterplot with a smoothing line to report your results. You may find facetting by region useful</li>
</ol>
<pre class="r"><code>#overall condition
fertility_gdp &lt;- ggplot(worldbank2, aes(x=NY.GDP.PCAP.KD, y=SP.DYN.TFRT.IN))+
  geom_point(aes(color=region), size=0.2)+
  ylim(0,10)+
  theme_bw()+
  geom_smooth(method = &quot;lm&quot;)+ 
  labs(title = &quot;Scatterplot of fertility rate and GDP per capita&quot;, y = &quot;fertility rate&quot;, x= &quot;GDP per capita&quot;)+
 # theme(legend.position = &quot;none&quot;)+
  xlim(0, 150000)
  NULL</code></pre>
<pre><code>## NULL</code></pre>
<pre class="r"><code>fertility_gdp</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/fertility_gdp-1.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#faceting by regions
fertility_gdp_region &lt;- new_dataset %&gt;% 
  # filter(year == 2011) %&gt;% 
  ggplot(aes(x=NY.GDP.PCAP.KD, y=SP.DYN.TFRT.IN))+
  geom_point(aes(color=country), size=0.2)+
  labs(title = &quot;Scatterplot of fertility rate and GDP per capita by region&quot;, y = &quot;Fertility rate&quot;, x= &quot;GDP per capita&quot;)+
  geom_smooth(method = &quot;lm&quot;)+
 # xlim(0,150000)+
  #ylim(30,90)+
  theme_bw()+
  facet_wrap(vars(region), scales = &quot;free&quot; )+
  theme(legend.position = &quot;none&quot;)+
  NULL

fertility_gdp_region</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/fertility_gdp-2.png" width="1056" style="display: block; margin: auto;" />
<em>As the scatterplot above indicates, there is a negative correlation between fertility rate and GDP per capita. This relationship is especially strong in regions that are typically less developed such as Sub-Saharan Africa and South Asia. In North America, the trendline is slightly positive, possibly due to the small sample size. Overall, Europe &amp; Central Asia have the lowest fertility rate and highest GDP per capita among all the regions.</em></p>
<ol start="3" style="list-style-type: decimal">
<li>Which regions have the most observations with missing HIV data? Generate a bar chart (<code>geom_col()</code>), in descending order.</li>
</ol>
<pre class="r"><code>hiv_missing &lt;- new_dataset %&gt;%
  group_by(region) %&gt;%
  summarize(n_missing(hiv_pct)) %&gt;%
  rename(&quot;hiv_missing_count&quot;=&quot;n_missing(hiv_pct)&quot;) 
  
hiv_miss &lt;- ggplot()+
  geom_col(data=hiv_missing, aes(x=hiv_missing_count, y=reorder(region,hiv_missing_count),fill=-hiv_missing_count))+
  #scale_fill_hue(c = 40)
  labs(title = &quot;Missing HIV data count by Region&quot;, y = &quot;Region&quot;, x= &quot;HIV missing count&quot;)+
  theme(legend.position = &quot;none&quot;)

hiv_miss</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/hiv_missing_data-1.png" width="1056" style="display: block; margin: auto;" />
<em>As the barchart indicates, the Sub-Saharan Africa has the most observations with 497 missing HIV data, followed by Europe &amp; Central Asia, which has 435 missing HIV data.</em></p>
<ol start="4" style="list-style-type: decimal">
<li>How has mortality rate under 5 changed by region? In each region, find the top 5 countries that have seen the greatest improvement, as well as those 5 countries where mortality rates have had the least improvement or even deterioration.</li>
</ol>
<pre class="r"><code>#How has mortality rate under 5 changed by region
mortality_by_region &lt;- ggplot(worldbank2, aes(x=year, y=SH.DYN.MORT))+
  geom_point(aes(color=country), size=0.2)+
  labs(title = &quot;Scatterplot of mortality rate by year per region&quot;, y = &quot;Mortality rate under 5&quot;, x= &quot;Year&quot;)+
  geom_smooth(method = &quot;lm&quot;)+
  theme_bw()+
  facet_wrap(vars(region), scales = &quot;free&quot; )+
  theme(legend.position = &quot;none&quot;)+
  NULL
  
mortality_by_region</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/mortality%20rate%20under%205%20change-1.png" width="1056" style="display: block; margin: auto;" />
<em>Overall, the mortality rate under 5 has declined since 1960. Among all of the regions, South Asia has the greatest improvement while North America has the least improvement.</em></p>
<pre class="r"><code>#top 5 countries that have seen the greatest improvement in each region

mortality_rate&lt;- worldbank2 %&gt;%
  select(country,region,year,SH.DYN.MORT)

# calculate the improvement  of mortality rate under 5 
mortality_improvement &lt;-mortality_rate %&gt;%
   na.omit()%&gt;%
   group_by(region,country) %&gt;%
   mutate(first_rate=first(SH.DYN.MORT),last_rate=last(SH.DYN.MORT))%&gt;%
   summarise(improvement= (first_rate-last_rate)/first_rate) 
  
mortality_improvement &lt;-  mortality_improvement[!duplicated(mortality_improvement ), ]


top_5_country &lt;-mortality_improvement %&gt;%
  group_by(region)%&gt;%
  slice_max(improvement, n=5)
top_5_country</code></pre>
<pre><code>## # A tibble: 32 × 3
## # Groups:   region [7]
##    region                country     improvement
##    &lt;chr&gt;                 &lt;chr&gt;             &lt;dbl&gt;
##  1 East Asia &amp; Pacific   Korea, Rep.       0.970
##  2 East Asia &amp; Pacific   Singapore         0.943
##  3 East Asia &amp; Pacific   Japan             0.932
##  4 East Asia &amp; Pacific   Thailand          0.930
##  5 East Asia &amp; Pacific   China             0.916
##  6 Europe &amp; Central Asia Portugal          0.969
##  7 Europe &amp; Central Asia Turkey            0.953
##  8 Europe &amp; Central Asia Italy             0.934
##  9 Europe &amp; Central Asia Cyprus            0.932
## 10 Europe &amp; Central Asia Poland            0.928
## # … with 22 more rows</code></pre>
<pre class="r"><code>least_5_country &lt;-mortality_improvement %&gt;%
  group_by(region)%&gt;%
  slice_min(improvement, n=5)
least_5_country</code></pre>
<pre><code>## # A tibble: 32 × 3
## # Groups:   region [7]
##    region                country               improvement
##    &lt;chr&gt;                 &lt;chr&gt;                       &lt;dbl&gt;
##  1 East Asia &amp; Pacific   Micronesia, Fed. Sts.       0.425
##  2 East Asia &amp; Pacific   Palau                       0.475
##  3 East Asia &amp; Pacific   Nauru                       0.543
##  4 East Asia &amp; Pacific   Tuvalu                      0.672
##  5 East Asia &amp; Pacific   Fiji                        0.680
##  6 Europe &amp; Central Asia Monaco                      0.649
##  7 Europe &amp; Central Asia Turkmenistan                0.682
##  8 Europe &amp; Central Asia Slovak Republic             0.718
##  9 Europe &amp; Central Asia Ukraine                     0.728
## 10 Europe &amp; Central Asia Moldova                     0.761
## # … with 22 more rows</code></pre>
<pre class="r"><code>top_5_country_bar &lt;- ggplot()+
  geom_col(data=top_5_country, aes(x=reorder(country,-improvement), y=improvement,fill=improvement))+
  facet_wrap(vars(region), scales = &quot;free_x&quot; )+
  labs(title = &quot;Top 5 countries that have greatest improvement&quot;, y = &quot;improvement&quot;, x= &quot;country&quot;)+
  #theme(legend.position = &quot;none&quot;)+
  NULL

top_5_country_bar</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/top%205%20countries%20greatest%20improvement%20in%20each%20region-1.png" width="1440" style="display: block; margin: auto;" /></p>
<pre class="r"><code>least_5_country_bar &lt;- ggplot()+
  geom_col(data=least_5_country, aes(x=reorder(country,-improvement), y=improvement,fill=improvement))+
  facet_wrap(vars(region), scales = &quot;free_x&quot; )+
  labs(title = &quot;Top 5 countries that have least improvement&quot;, y = &quot;improvement&quot;, x= &quot;country&quot;)+
  #theme(legend.position = &quot;none&quot;)+
  NULL

least_5_country_bar </code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/top%205%20countries%20greatest%20improvement%20in%20each%20region-2.png" width="1440" style="display: block; margin: auto;" />
<em>The tables above show the Top 5 countries that have experienced the greatest/least improvement in mortality rate from 1960 to 2016 by region. For instance, in east Asia &amp; Pacific Korea, Rep., Singapore, Japan, Thailand and China have made the greatest improvement while in Micronesia Palau, Nauru, Tuvalu and Fiji have made the least improvement. As for South Asia and North America, since the number of the countries is less than 10, the Top 5 and Last 5 are not very representative. We didn’t observe that there is any deterioration in mortality rate so far. The country that experienced the least improvement is Somalia in Sub-Saharan Africa with 0.346 improvement.</em></p>
<ol start="5" style="list-style-type: decimal">
<li>Is there a relationship between primary school enrollment and fertility rate?</li>
</ol>
<pre class="r"><code>school_fertility &lt;- ggplot(worldbank2, aes(x=SE.PRM.NENR, y=SP.DYN.TFRT.IN))+
  geom_point(aes(color=region), size=0.5)+
  labs(title = &quot;Scatterplot of fertility rate and primary school enrollment&quot;, y = &quot;fertility rate&quot;, x= &quot;primary school enrollment&quot;)+
  geom_smooth(method = &quot;lm&quot;)+
  theme_bw()+
  NULL
school_fertility</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/school_enrollment_vs_fertility_rate-1.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>school_fertility_region &lt;- ggplot(worldbank2, aes(x=SE.PRM.NENR, y=SP.DYN.TFRT.IN))+
  geom_point(aes(color=region), size=0.2)+
  labs(title = &quot;Scatterplot of fertility rate and primary school enrollment by region&quot;, y = &quot;fertility rate&quot;, x= &quot;primary school enrollment&quot;)+
  geom_smooth(method = &quot;lm&quot;)+
  theme_bw()+
  facet_wrap(vars(region), scales = &quot;free&quot; )+
  theme(legend.position = &quot;none&quot;)+
  NULL
school_fertility_region</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/school_enrollment_vs_fertility_rate-2.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>fertility_change &lt;- ggplot(worldbank2, aes(x=year, y=SP.DYN.TFRT.IN))+
  geom_point(aes(color=country), size=0.2)+
  labs(title = &quot;Scatterplot of fertility rate by year per region&quot;, y = &quot;fertility rate&quot;, x= &quot;year&quot;)+
  geom_smooth(method = &quot;lm&quot;)+
  theme_bw()+
  facet_wrap(vars(region), scales = &quot;free&quot; )+
  theme(legend.position = &quot;none&quot;)+
  NULL
fertility_change</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/school_enrollment_vs_fertility_rate-3.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>enrollment_change&lt;- ggplot(worldbank2, aes(x=year, y=SE.PRM.NENR))+
  geom_point(aes(color=country), size=0.2)+
  labs(title = &quot;Scatterplot of primary school enrollment rate by year per region&quot;, y = &quot;primary school enrollment&quot;, x= &quot;year&quot;)+
  geom_smooth(method = &quot;lm&quot;)+
  theme_bw()+
  facet_wrap(vars(region), scales = &quot;free&quot; )+
  theme(legend.position = &quot;none&quot;)+
  xlim(1970,2011)
  NULL</code></pre>
<pre><code>## NULL</code></pre>
<pre class="r"><code>enrollment_change</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/school_enrollment_vs_fertility_rate-4.png" width="1056" style="display: block; margin: auto;" /></p>
<p><em>As the first and second scatterplot above indicates, there is a negative correlation between fertility rate and primary school enrollment rate. To explore the reason, we took a further look at how fertility rate and primary school enrollment rate have changed from 1960 to 2016 by each country in the respective regions. We can observe an obvious fertility rate decline as well as a rise in primary school enrollment which indicates the overall educational level has improved over the years. This may furthermore explain the negative correlation between fertility rate and primary school enrollment rate.</em></p>
</div>
<div id="challenge-1-excess-rentals-in-tfl-bike-sharing" class="section level1">
<h1>Challenge 1: Excess rentals in TfL bike sharing</h1>
<pre class="r"><code>url &lt;- &quot;https://data.london.gov.uk/download/number-bicycle-hires/ac29363e-e0cb-47cc-a97a-e216d900a6b0/tfl-daily-cycle-hires.xlsx&quot;

# Download TFL data to temporary file
httr::GET(url, write_disk(bike.temp &lt;- tempfile(fileext = &quot;.xlsx&quot;)))</code></pre>
<pre><code>## Response [https://airdrive-secure.s3-eu-west-1.amazonaws.com/london/dataset/number-bicycle-hires/2021-08-23T14%3A32%3A29/tfl-daily-cycle-hires.xlsx?X-Amz-Algorithm=AWS4-HMAC-SHA256&amp;X-Amz-Credential=AKIAJJDIMAIVZJDICKHA%2F20210919%2Feu-west-1%2Fs3%2Faws4_request&amp;X-Amz-Date=20210919T141006Z&amp;X-Amz-Expires=300&amp;X-Amz-Signature=372fa9baa0df1d558880f7ea164793dc87264dc57925c3f2814aec9c768cd6f9&amp;X-Amz-SignedHeaders=host]
##   Date: 2021-09-19 14:13
##   Status: 200
##   Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
##   Size: 173 kB
## &lt;ON DISK&gt;  /var/folders/43/_83zd4gn2sx502x88934l6tr0000gn/T//RtmpOU2MzN/file46a7730b0e4.xlsx</code></pre>
<pre class="r"><code># Use read_excel to read it as dataframe
bike0 &lt;- read_excel(bike.temp,
                   sheet = &quot;Data&quot;,
                   range = cell_cols(&quot;A:B&quot;))

# change dates to get year, month, and week
bike &lt;- bike0 %&gt;% 
  clean_names() %&gt;% 
  rename (bikes_hired = number_of_bicycle_hires) %&gt;% 
  mutate (year = year(day),
          month = lubridate::month(day, label = TRUE),
          week = isoweek(day),
          single_day = day(day))</code></pre>
<p>We can easily create a facet grid that plots bikes hired by month and year.</p>
<pre class="r"><code>library(scales)
facet_monthly_bike_rentals &lt;- bike %&gt;%
  filter(year &gt;= 2015)%&gt;%
  ggplot(aes(x = bikes_hired))+
    geom_density()+
    facet_grid(vars(year), vars(month))+
  
    scale_x_continuous(labels = number_format(scale = 1/1000, suffix = &quot;K&quot;))+
  
    theme(axis.text.y = element_blank(), plot.background = element_blank(), panel.background = element_blank(), panel.grid = element_line(color = &quot;lightgrey&quot;), strip.background = element_blank())+
  
    labs(title = &quot;Distribution of bikes hired per month&quot;, x = &quot;Bike Rentals&quot;)
    

facet_monthly_bike_rentals</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/facet_bike_rentals-1.png" width="1440" style="display: block; margin: auto;" /></p>
<p>Look at May and Jun and compare 2020 with the previous years. What’s happening?</p>
<p><em>It is observable, that the distribution of bike rentals in May and June tends to be more concentrated and centralised around 40,000 daily bike rentals than in many of the other months. This might be due to the fact that temperatures and the overall weather is more stable in these months, and thus there is less fluctuation in daily demand.</em>
<em>Looking at the overall distribution of bike rentals in 2020 compared to the previous years, the first two months seem similar. However, starting from March, a shift in distribution towards the left, can be seen, indicating that bike rentals incurred a period of less demand. This can likely be attributed to the outbreak of the COVID19 pandemic, and people staying home more frequently. This trend continues until the month of June, from which bike rentals follow the previous years’ distributions more closely once again.</em></p>
<pre class="r"><code>monthly_mean &lt;- bike %&gt;%
  filter(year %in% c(2016, 2017, 2018, 2019)) %&gt;% #We filter for these years, as they are the only ones relevant to the calculation of the mean
  group_by(month) %&gt;%
  summarise(mean_demand = mean(bikes_hired)) #we calculate the mean bike rentals per month for the period from 2016 until 2019</code></pre>
<pre class="r"><code># We need to make month numeric in order for the line plot to be displayed properly.

month &lt;- c(&quot;Jan&quot;, &quot;Feb&quot;, &quot;Mar&quot;, &quot;Apr&quot;, &quot;May&quot;, &quot;Jun&quot;, &quot;Jul&quot;, &quot;Aug&quot;, &quot;Sep&quot;, &quot;Oct&quot;, &quot;Nov&quot;, &quot;Dec&quot;)
mon_num &lt;- 1:12

df_month &lt;- tibble(month, mon_num)
df_month #we allocate each number to the respective month, so that we can bind the numbers to the actual bike data table</code></pre>
<pre><code>## # A tibble: 12 × 2
##    month mon_num
##    &lt;chr&gt;   &lt;int&gt;
##  1 Jan         1
##  2 Feb         2
##  3 Mar         3
##  4 Apr         4
##  5 May         5
##  6 Jun         6
##  7 Jul         7
##  8 Aug         8
##  9 Sep         9
## 10 Oct        10
## 11 Nov        11
## 12 Dec        12</code></pre>
<pre class="r"><code>bike_diff &lt;- bike %&gt;%
  left_join(df_month, by = &quot;month&quot;) %&gt;% 
  left_join(monthly_mean, by = &quot;month&quot;) %&gt;% #We join the monthly mean (2016-2019) and the month numbers to the bike data table
  group_by(year, month, mon_num) %&gt;% 
  summarise(bikes_hired_month_avg = mean(bikes_hired), mean_demand = mean(mean_demand), mon_num = mean(mon_num)) %&gt;% #we calculate the actual mean of bike rentals per month. Compared to the other mean however, we limit this calculation to just the respective year, instead of across the four years from 2016 - 2019
  mutate(diff_exp = mean_demand - bikes_hired_month_avg, less_than_mean = if_else(diff_exp &gt;= 0, -diff_exp, 0), more_than_mean = if_else(diff_exp &lt; 0, -diff_exp, 0)) #we introduce two new variables, that either become the difference between the present month&#39;s mean and the total mean or 0, depending on the sign of the difference. We introduce this variable, in order to be able to differentiate between when to colour our ribbon red or green at a later stage.


plotActualForecast &lt;- bike_diff %&gt;% 
  filter(year %in% c(2016, 2017, 2018, 2019, 2020, 2021)) %&gt;% 
  
  ggplot(aes(x = mon_num))+

    geom_line(aes(y = bikes_hired_month_avg))+
    geom_line(aes(y = mean_demand), color = &quot;#2d0fd7&quot;, size = 1)+

    geom_ribbon(aes(ymin = mean_demand, ymax = mean_demand + more_than_mean), fill = &quot;#7DCD85&quot;, alpha = 0.4)+ 
    geom_ribbon(aes(ymin = mean_demand, ymax = mean_demand + less_than_mean), fill = &quot;#CB454A&quot;, alpha = 0.4)+ #here we go ahead with our implementation of different colour per ribbon, depending on whether the actual monthly mean is bigger than the overall one or not. This is done by varying the upper limit in ymax: If we don&#39;t want one colour, this upper limit is essentially equal to the lower one such that no ribbon gets drawn.

    facet_wrap(vars(year))+
  
    labs(title = &quot;Monthly changes in TFL bike rentals&quot;, subtitle = &quot;Change from monthly average shown in blue and calculated between 2016 and 2019&quot;, x =&quot;Month&quot;, y = &quot;Bike Rentals&quot;)+
  
    scale_x_discrete(limits = month)+
  
    theme_bw()+
    theme(strip.background = element_blank())

plotActualForecast</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/plot_bike_diff-1.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>weekly_mean &lt;- bike %&gt;%
  filter(year %in% c(2016, 2017, 2018, 2019, 2020, 2021)) %&gt;% 
  select(&quot;bikes_hired&quot;, &quot;week&quot;) %&gt;% 
  group_by(week) %&gt;% 
  summarise(weekly_avg = mean(bikes_hired)) #similarly to the overall month mean, we calculate the overall week mean</code></pre>
<pre class="r"><code>joinedWeeklyBike &lt;- bike %&gt;% 
  left_join(weekly_mean, by = &quot;week&quot;) %&gt;% #we join the overall weekly averages with the actual data table
  select(&quot;year&quot;, &quot;week&quot;, &quot;bikes_hired&quot;, &quot;weekly_avg&quot;) %&gt;% 
  group_by(year, week) %&gt;% 
  summarise(actual_week_avg = mean(bikes_hired), weekly_avg = mean(weekly_avg)) %&gt;% 
  mutate(percChange = (actual_week_avg-weekly_avg)/weekly_avg) #we calculate the percentage change, which we plot against the weeks</code></pre>
<pre class="r"><code>joinedWeeklyBike &lt;- joinedWeeklyBike %&gt;% 
  filter(year %in% c(2016, 2017, 2018, 2019, 2020, 2021))

plotWeeklyBike &lt;- joinedWeeklyBike %&gt;% 
  ggplot(aes(x = week))+
    geom_line(aes(y = percChange))+
  
    geom_ribbon(aes(ymin = 0, ymax = if_else(percChange &gt;= 0, percChange, 0)), fill = &quot;#7DCD85&quot;, alpha = 0.4)+
    geom_ribbon(aes(ymin = if_else(percChange &lt; 0, percChange, 0), ymax = 0), fill = &quot;#CB454A&quot;, alpha = 0.4)+ #we vary the lower and upper limits of the ribbon, in order to accurately fill the area between the graph and the x axis
  
    geom_rug(data = joinedWeeklyBike, sides = &quot;b&quot;, colour = if_else(joinedWeeklyBike$percChange &gt;= 0,&quot;#7DCD85&quot;,&quot;#CB454A&quot;))+ #we include geom_rug to depict the small lines above the x axis, indicating a positive or negative value of percentage change in either green or red
    
    facet_wrap(vars(year))+
  
    theme_bw()

plotWeeklyBike</code></pre>
<p><img src="/blogs/hw2-twice_files/figure-html/plot_bike_weekly-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p>Should you use the mean or the median to calculate your expected rentals? Why?</p>
<p><em>It makes sense to use the mean for calculating expected rentals, as we really need to take very low and very high numbers into consideration. If one were to use the median, and thereby ignore outlying values, the supply might not be well prepared for keeping up with demand on specific days.</em></p>
</div>
<div id="deliverables" class="section level1">
<h1>Deliverables</h1>
<p>As usual, there is a lot of explanatory text, comments, etc. You do not need these, so delete them and produce a stand-alone document that you could share with someone. Knit the edited and completed R Markdown file as an HTML document (use the “Knit” button at the top of the script editor window) and upload it to Canvas.</p>
</div>
<div id="details" class="section level1">
<h1>Details</h1>
<ul>
<li>Who did you collaborate with: <em>Group 3 (Jiaying Chen, Yingjin He, Sabrina Seow, Kashish Solanki, Roman Vazquez Lorenzo, Maximilian Stock)</em></li>
<li>Approximately how much time did you spend on this problem set: <em>12 hours</em></li>
<li>What, if anything, gave you the most trouble: <em>Finding a proper way to switch between red and green colours when using geom_ribbon</em></li>
</ul>
</div>
