---
categories:
- ""
- ""
date: "2017-10-31T21:28:43-05:00"
description: ""
draft: false
image: ""
keywords: ""
slug: ipsum
title: Homework 3 for Applied Statistics 
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<p>Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns. You will work with a selected group of variables from a random sample of observations during one of the years the YRBSS was conducted.</p>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it. There are observations on 13 different variables, some categorical and some numerical. The meaning of each variable can be found by bringing up the help file:</p>
<p>?yrbss</p>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1…
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fema…
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, …
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not&quot;…
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Africa…
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1…
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71.2, …
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not …
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did not…
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, …
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;,…
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, …
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5&quot;…</code></pre>
<p>Before you carry on with your analysis, it’s is always a good idea to check with <code>skimr::skim()</code> to get a feel for missing values, summary statistics of numerical variables, and a very rough histogram.</p>
<pre class="r"><code>skim(yrbss)</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-2">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>You will first start with analyzing the <code>weight</code> of participants in kilograms. Using visualization and summary statistics, describe the distribution of weights. How many observations are we missing weights from?</p>
<p><em>From the histogram below we can observe that the distribution of weight is right-skewed - most people remain within the 50 to 80kg while there are several individuals that go above that, forming the right tail. It is important to note that we are missing 1004 weight and height measurements, which we can observe from the <code>n_missing</code> statistic</em></p>
<pre class="r"><code>weight_hist &lt;- ggplot(yrbss, aes(x = weight, fill = gender))+
  geom_histogram(bins = 50)+
  
  geom_vline(aes(xintercept = median(weight)), linetype = 2)+
  
  labs(title = &quot;Distribution of weight&quot;, subtitle = &quot;Youth Risk Behaviour Surveillence Dataset Analysis&quot;,  x = &quot;Weight (kg)&quot;, y = &quot;Count&quot;)
  
  theme_stata()+
  theme(plot.background = element_blank())

weight_hist</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/eda_on_weight-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p>Next, consider the possible relationship between a high schooler’s weight and their physical activity. Plotting the data is a useful first step because it helps us quickly visualize trends, identify strong associations, and develop research questions.</p>
<pre class="r"><code>weight_physAct &lt;- ggplot(na.omit(yrbss), aes(x = as.factor(physically_active_7d), y = weight))+
  geom_boxplot(fill=&quot;red&quot;, alpha=0.2)+
  stat_summary(fun.y=mean, geom=&quot;point&quot;, shape=20, size=2, color=&quot;brown&quot;)+
  labs(title = &quot;High Schoolers: Weight and Physical Activity&quot;, subtitle = &quot;Boxplot showing relationship between weight and number of days of physical activity per week&quot;, x = &quot;Number of days of physical activity per week&quot;, y = &quot;Weight (Kg)&quot;)
  NULL</code></pre>
<pre><code>## NULL</code></pre>
<pre class="r"><code>weight_physAct</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/weight_physActivity-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p>Let’s create a new variable in the dataframe <code>yrbss</code>, called <code>physical_3plus</code> , which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise. You may also want to calculate the number and % of those who are and are not active for more than 3 days. Use the <code>count()</code> function and see if you get the same results as <code>group_by()... summarise()</code></p>
<pre class="r"><code># Create physical_3plus variable
yrbss_adj &lt;- yrbss %&gt;% 
  mutate(physical_3plus = if_else(physically_active_7d &gt;= 3, &quot;Yes&quot;, &quot;No&quot;)) # Create physical_3plus variable
yrbss_adj</code></pre>
<pre><code>## # A tibble: 13,583 × 14
##      age gender grade hispanic race    height weight helmet_12m text_while_driv…
##    &lt;int&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;    &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;           
##  1    14 female 9     not      Black …  NA      NA   never      0               
##  2    14 female 9     not      Black …  NA      NA   never      &lt;NA&gt;            
##  3    15 female 9     hispanic Native…   1.73   84.4 never      30              
##  4    15 female 9     not      Black …   1.6    55.8 never      0               
##  5    15 female 9     not      Black …   1.5    46.7 did not r… did not drive   
##  6    15 female 9     not      Black …   1.57   67.1 did not r… did not drive   
##  7    15 female 9     not      Black …   1.65  132.  did not r… &lt;NA&gt;            
##  8    14 male   9     not      Black …   1.88   71.2 never      &lt;NA&gt;            
##  9    15 male   9     not      Black …   1.75   63.5 never      &lt;NA&gt;            
## 10    15 male   10    not      Black …   1.37   97.1 did not r… &lt;NA&gt;            
## # … with 13,573 more rows, and 5 more variables: physically_active_7d &lt;int&gt;,
## #   hours_tv_per_school_day &lt;chr&gt;, strength_training_7d &lt;int&gt;,
## #   school_night_hours_sleep &lt;chr&gt;, physical_3plus &lt;chr&gt;</code></pre>
<pre class="r"><code># Proportion using group_by and summarise
proportion_weight &lt;- yrbss_adj %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarise(n = sum(!is.na(physical_3plus))) %&gt;% # Omit NA values
  mutate(prop_perc = n/sum(n)*100)
proportion_weight</code></pre>
<pre><code>## # A tibble: 3 × 3
##   physical_3plus     n prop_perc
##   &lt;chr&gt;          &lt;int&gt;     &lt;dbl&gt;
## 1 No              4404      33.1
## 2 Yes             8906      66.9
## 3 &lt;NA&gt;               0       0</code></pre>
<pre class="r"><code># Proportion using count method
num_yes &lt;- count(yrbss_adj$physical_3plus == &quot;Yes&quot;) # Count number of people physically active &gt;3 days a week
num_no &lt;- count(yrbss_adj$physical_3plus == &quot;No&quot;) # Count number of people physically active &lt;3 days a week
num_total = (num_yes+num_no)
perc_yes = num_yes/num_total*100
perc_no = num_no/num_total*100
count_method_df &lt;- tibble(values = 
                          c(&quot;Yes&quot;, &quot;No&quot;, &quot;Total&quot;), 
                          count = c(num_no, num_yes, num_total), 
                          prop_perc = c(perc_no, perc_yes, 100))
count_method_df</code></pre>
<pre><code>## # A tibble: 3 × 3
##   values count prop_perc
##   &lt;chr&gt;  &lt;int&gt;     &lt;dbl&gt;
## 1 Yes     4404      33.1
## 2 No      8906      66.9
## 3 Total  13310     100</code></pre>
<p>Can you provide a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week?</p>
<pre class="r"><code>Notactive_3daysormore &lt;-  prop.test(as.double(count_method_df[1,&quot;count&quot;]), as.double(count_method_df[3,&quot;count&quot;])) # Create test to obtain 95% CI interval

Notactive_3daysormore</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  as.double out of as.doublecount_method_df[1, &quot;count&quot;] out of count_method_df[3, &quot;count&quot;]
## X-squared = 1522, df = 1, p-value &lt;2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.323 0.339
## sample estimates:
##     p 
## 0.331</code></pre>
<p><em>The confidence interval for the proportion of high schoolers that are active for at least 3 days a week based on out sample ranges from 32.3% to 33.9%</em></p>
<p>Make a boxplot of <code>physical_3plus</code> vs. <code>weight</code>. Is there a relationship between these two variables? What did you expect and why?</p>
<p><em>There does not seem to be a clear relationship between both variables. Initially, one can expect that people who exercise more (3 or more days a week) would be more in shape and therefore weight less. However, from the boxplot it is observed that this is not true, as for this dataset people who exercise 3 or more days weights more than the ones who don’t. Weight can be influenced by many other aspects, such as height, nutrition and muscle mass, hence the initial hypothesis of a negative relationship between weight and physical activity can be discarded.</em></p>
<pre class="r"><code>boxplot_activity_weight &lt;- yrbss_adj %&gt;%
  filter(is.na(physical_3plus) == FALSE ) %&gt;% # Omit NA values
  ggplot()+
  geom_boxplot(aes(x = physical_3plus, y = weight), fill=&quot;red&quot;, alpha=0.2)+
  labs(title = &quot;High Schoolers: Weight and Physical Activity&quot;, subtitle = &quot;Boxplot showing relationship between weight and people who exercise more or less than 3 days a week&quot;, x = &quot;Physically active 3 or more days a week&quot;, y = &quot;Weight (Kg)&quot;)+
  theme_bw()+
  NULL

boxplot_activity_weight</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/boxplot_activity_weight-1.png" width="1056" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval" class="section level2">
<h2>Confidence Interval</h2>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. Note that when we calculate the mean, SD, etc. weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</p>
<pre class="r"><code>means_weight &lt;- yrbss_adj %&gt;% 
  filter(is.na(physical_3plus) == FALSE ) %&gt;% # Omit NA values
  group_by(physical_3plus) %&gt;% 
  summarise(n = n(), mean_group = mean(weight, na.rm = TRUE), SD = sd(weight, na.rm = TRUE), SE = SD/sqrt(n), t_crit = qt(0.975, n - 1), lower_lim = mean_group - t_crit*SE, upper_lim = mean_group + t_crit*SE)
  
means_weight</code></pre>
<pre><code>## # A tibble: 2 × 8
##   physical_3plus     n mean_group    SD    SE t_crit lower_lim upper_lim
##   &lt;chr&gt;          &lt;int&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 No              4404       66.7  17.6 0.266   1.96      66.2      67.2
## 2 Yes             8906       68.4  16.5 0.175   1.96      68.1      68.8</code></pre>
<p><em>There is an observed difference of about 1.7kg (68.4 - 66.7), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</em></p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p>Write the null and alternative hypotheses for testing whether mean weights are different for those who exercise at least 3? times a week and those who don’t.</p>
<p><em>Claim (Null hypothesis):</em> <span class="math inline">\(H0: \delta = 0\)</span>* <em>There is no difference in means across the groups</em></p>
<p><em>Alternative hypothesis:</em> <span class="math inline">\(H_a: \delta\)</span>* <em>There is a difference in means across the groups</em></p>
<p><em>We test the difference between means of the two directors, and the t-stat value equals 3 (greater than t-critical), while the p-value is 0.01 (&gt;5%). The confidence interval is [0.16,1.13] and does not contain the value 0. Therefore, we reject H0 and can conclude that the mean ratings of Spielberg and Burton are significantly different.</em></p>
<pre class="r"><code>t.test(weight ~ physical_3plus, data = yrbss_adj)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means between group No and group Yes is not equal to 0
## 95 percent confidence interval:
##  -2.42 -1.12
## sample estimates:
##  mean in group No mean in group Yes 
##              66.7              68.4</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Next, we will introduce a new function, <code>hypothesize</code>, that falls into the infer workflow. You will use this method for conducting hypothesis tests.</p>
<p>But first, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code>obs_diff &lt;- yrbss_adj %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;Yes&quot;, &quot;No&quot;))

obs_diff</code></pre>
<pre><code>## Response: weight (numeric)
## Explanatory: physical_3plus (factor)
## # A tibble: 1 × 1
##    stat
##   &lt;dbl&gt;
## 1  1.77</code></pre>
<p>Notice how you can use the functions specify and calculate again like you did for calculating confidence intervals. Here, though, the statistic you are searching for is the difference in means, with the order being yes - no != 0 (Alternative).</p>
<p>After you have initialized the test, you need to simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code>null_dist &lt;- yrbss_adj %&gt;%
  # specify variables
  specify(weight ~ physical_3plus) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;Yes&quot;, &quot;No&quot;))

null_dist</code></pre>
<pre><code>## Response: weight (numeric)
## Explanatory: physical_3plus (factor)
## Null Hypothesis: independence
## # A tibble: 1,000 × 2
##    replicate    stat
##        &lt;int&gt;   &lt;dbl&gt;
##  1         1 -0.0314
##  2         2 -0.315 
##  3         3 -0.0425
##  4         4  0.272 
##  5         5  0.119 
##  6         6  0.640 
##  7         7  0.0389
##  8         8 -0.289 
##  9         9 -0.0289
## 10        10  0.218 
## # … with 990 more rows</code></pre>
<p>Here, <code>hypothesize</code> is used to set the null hypothesis as a test for independence, i.e., that there is no difference between the two population means. In one sample cases, the null argument can be set to <em>point</em> to test a hypothesis relative to a point estimate.</p>
<p>Also, note that the <code>type</code> argument within generate is set to permute, which is the argument when generating a null distribution for a hypothesis test.</p>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()+
  theme_bw()</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/unnamed-chunk-3-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we can visualise to see how many of these null permutations have a difference of at least <code>obs_stat</code> of 1.77?</p>
<pre class="r"><code>obs_stat &lt;- obs_diff %&gt;% pull() %&gt;% round(2)
obs_stat</code></pre>
<pre><code>## [1] 1.77</code></pre>
<p>We can also calculate the p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)+
  theme_bw()</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/unnamed-chunk-5-1.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>This the standard workflow for performing hypothesis tests.</p>
</div>
</div>
<div id="imdb-ratings-differences-between-directors" class="section level1">
<h1>IMDB ratings: Differences between directors</h1>
<p>Recall the IMBD ratings data. I would like you to explore whether the mean IMDB rating for Steven Spielberg and Tim Burton are the same or not. I have already calculated the confidence intervals for the mean ratings of these two directors and as you can see they overlap.</p>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
glimpse(movies)</code></pre>
<pre><code>## Rows: 2,961
## Columns: 11
## $ title               &lt;chr&gt; &quot;Avatar&quot;, &quot;Titanic&quot;, &quot;Jurassic World&quot;, &quot;The Avenge…
## $ genre               &lt;chr&gt; &quot;Action&quot;, &quot;Drama&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;…
## $ director            &lt;chr&gt; &quot;James Cameron&quot;, &quot;James Cameron&quot;, &quot;Colin Trevorrow…
## $ year                &lt;dbl&gt; 2009, 1997, 2015, 2012, 2008, 1999, 1977, 2015, 20…
## $ duration            &lt;dbl&gt; 178, 194, 124, 173, 152, 136, 125, 141, 164, 93, 1…
## $ gross               &lt;dbl&gt; 7.61e+08, 6.59e+08, 6.52e+08, 6.23e+08, 5.33e+08, …
## $ budget              &lt;dbl&gt; 2.37e+08, 2.00e+08, 1.50e+08, 2.20e+08, 1.85e+08, …
## $ cast_facebook_likes &lt;dbl&gt; 4834, 45223, 8458, 87697, 57802, 37723, 13485, 920…
## $ votes               &lt;dbl&gt; 886204, 793059, 418214, 995415, 1676169, 534658, 9…
## $ reviews             &lt;dbl&gt; 3777, 2843, 1934, 2425, 5312, 3917, 1752, 1752, 35…
## $ rating              &lt;dbl&gt; 7.9, 7.7, 7.0, 8.1, 9.0, 6.5, 8.7, 7.5, 8.5, 7.2, …</code></pre>
<pre class="r"><code>burton_spielberg &lt;- movies %&gt;% 
  filter(director %in% c(&quot;Steven Spielberg&quot;, &quot;Tim Burton&quot;)) %&gt;% 
  group_by(director) %&gt;% 
  summarise(mean=mean(rating),
            count=n(),
            t_critical = qt(0.975, count-1),
            se = sd(rating)/sqrt(count),
            margin_of_error = t_critical*se,
            lower_ci = mean - margin_of_error,
            higher_ci = mean + margin_of_error)
burton_spielberg</code></pre>
<pre><code>## # A tibble: 2 × 8
##   director          mean count t_critical    se margin_of_error lower_ci higher_ci
##   &lt;chr&gt;            &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt; &lt;dbl&gt;           &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 Steven Spielberg  7.57    23       2.07 0.145           0.301     7.27      7.87
## 2 Tim Burton        6.93    16       2.13 0.187           0.399     6.53      7.33</code></pre>
<pre class="r"><code>plot &lt;- ggplot(burton_spielberg, aes(x=mean, y=reorder(director, mean), colour = director))+
  geom_errorbar(width = 0.05, aes(xmin = lower_ci, xmax = higher_ci), size = 2)+
  geom_point(aes(x=mean), size = 5)+
  geom_rect(aes(xmin = max(lower_ci), xmax = min(higher_ci), ymin = Inf, ymax = Inf),
            fill=&quot;gray&quot;, colour=&quot;gray&quot;,alpha = 0.3)+
  theme_bw() +
  geom_text(aes(x=mean, label = round(mean, digits=2)),
            size = 8, vjust = 2, color = &quot;black&quot;)+
  geom_text(aes(x=lower_ci, label=round(lower_ci,digits=2)),
            size = 6, vjust = 2, color = &quot;black&quot;)+
  geom_text(aes(x=higher_ci, label=round(higher_ci,digits=2)),
            size = 6, vjust = 2, colour = &quot;black&quot;)+
  labs(title = &quot;Do Spielberg ad Burton have the same IMDB ratings?&quot;, 
       subtitle = &quot;95% confidence intervals overlap&quot;, x=&quot;Mean IMDB Rating&quot;, y=&quot;&quot;)+
  theme(plot.title=element_text(size=12,face=&quot;bold&quot;),
        axis.text = element_text(size=10),
        legend.position = &quot;none&quot;)
plot</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/replicating%20the%20plot-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p><em>Null Hypothesis H0: Average Rating for Spielberg - Average Rating for Burton = 0</em> <em>Alternative Hypothesis H1: Difference in Means not equal to 0.</em></p>
<pre class="r"><code>testrating &lt;- movies %&gt;% 
  filter(director %in% c(&quot;Steven Spielberg&quot;, &quot;Tim Burton&quot;)) %&gt;% 
  select(director, rating)

t.test(testrating$rating ~ testrating$director)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  testrating$rating by testrating$director
## t = 3, df = 31, p-value = 0.01
## alternative hypothesis: true difference in means between group Steven Spielberg and group Tim Burton is not equal to 0
## 95 percent confidence interval:
##  0.16 1.13
## sample estimates:
## mean in group Steven Spielberg       mean in group Tim Burton 
##                           7.57                           6.93</code></pre>
<p><em>We test the difference between means of the two directors, and the t-stat value equals 3 while the p-value is 0.01. The confidence interval is [0.16,1.13] and does not contain the value 0. The t-statistics value is greater than 2, p-value &lt; 5% and 0 lies outside the confidence interval, therefore we reject H0.</em></p>
<pre class="r"><code>obs_diff1 &lt;- testrating %&gt;%
  specify(rating ~ director) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;Steven Spielberg&quot;, &quot;Tim Burton&quot;))
obs_diff1</code></pre>
<pre><code>## Response: rating (numeric)
## Explanatory: director (factor)
## # A tibble: 1 × 1
##    stat
##   &lt;dbl&gt;
## 1 0.643</code></pre>
<pre class="r"><code>null_dist1 &lt;- testrating %&gt;%
  # specify variables
  specify(rating ~ director) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;Steven Spielberg&quot;, &quot;Tim Burton&quot;))

null_dist1</code></pre>
<pre><code>## Response: rating (numeric)
## Explanatory: director (factor)
## Null Hypothesis: independence
## # A tibble: 1,000 × 2
##    replicate    stat
##        &lt;int&gt;   &lt;dbl&gt;
##  1         1 -0.248 
##  2         2  0.0386
##  3         3  0.0704
##  4         4  0.0174
##  5         5  0.346 
##  6         6 -0.120 
##  7         7 -0.0674
##  8         8  0.155 
##  9         9  0.113 
## 10        10  0.208 
## # … with 990 more rows</code></pre>
<pre class="r"><code>ggplot(data = null_dist1, aes(x = stat)) +
  geom_histogram()+
  theme_bw()</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/unnamed-chunk-9-1.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>obs_stat1 &lt;- obs_diff1 %&gt;% pull() %&gt;% round(2)
obs_stat1</code></pre>
<pre><code>## [1] 0.64</code></pre>
<pre class="r"><code>null_dist1 %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff1, direction = &quot;two-sided&quot;)+
  theme_bw()</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/unnamed-chunk-11-1.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist1 %&gt;%
  get_p_value(obs_stat = obs_diff1, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1   0.008</code></pre>
</div>
<div id="omega-group-plc--pay-discrimination" class="section level1">
<h1>Omega Group plc- Pay Discrimination</h1>
<p>At the last board meeting of Omega Group Plc., the headquarters of a large multinational company, the issue was raised that women were being discriminated in the company, in the sense that the salaries were not the same for male and female executives. A quick analysis of a sample of 50 employees (of which 24 men and 26 women) revealed that the average salary for men was about 8,700 higher than for women. This seemed like a considerable difference, so it was decided that a further analysis of the company salaries was warranted.</p>
<p>You are asked to carry out the analysis. The objective is to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<div id="loading-the-data" class="section level2">
<h2>Loading the data</h2>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, 635…
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;ma…
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24, 3…</code></pre>
</div>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship (Salary - Gender)</h2>
<p>The data frame <code>omega</code> contains the salaries for the sample of 50 executives in the company. Can you conclude that there is a significant difference between the salaries of the male and female executives?</p>
<p><em>We will be performing two analyses - (1) Confidence Intervals and (2) Hypothesis Testing, and see if both lead to the same conclusion.</em></p>
<div id="two-separate-confidence-intervals" class="section level3">
<h3>Two Separate Confidence Intervals</h3>
<pre class="r"><code># Summary Statistics of salary by gender
mosaic::favstats (salary ~ gender, data=omega)

# Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, the t-critical value, the standard error, the margin of error, and the low/high endpoints of a 95% condifence interval
formula_ci_salary &lt;- omega %&gt;% 
  group_by(gender) %&gt;% 
  summarise(mean_salary = mean(salary),
            sd_salary = sd(salary),
            count = n(),
            
            # get t-critical value with (n-1) degrees of freedom
            t_critical = qt(0.975, count-1),
            se = sd_salary/sqrt(count),
            margin_of_error = t_critical * se,
            ci_low = mean_salary - margin_of_error,
            ci_high = mean_salary + margin_of_error
            ) 

formula_ci_salary</code></pre>
<pre class="r"><code>ggplot(formula_ci_salary, 
       aes(x=mean_salary,
           y=gender,
           colour=gender)) +   
  geom_point() +
  scale_colour_manual(values = c(&quot;red&quot;,&quot;blue&quot;)) +
  geom_errorbar(width=.2, aes(xmax = ci_high, xmin = ci_low)) +
  
  scale_x_continuous(labels = number)</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/visualise_ci_salary-1.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>  theme_bw() +
  labs(title = &quot;Which gender has a higher salary?&quot;, 
       x = &quot;Mean salary&quot;, 
       y = &quot;Gender&quot;) +
  NULL</code></pre>
<p><em>Interpretation: In this analysis, we compared the confidence intervals for the mean salaries of men and women to determine whether the difference between the two means is statistically significant. Based on our analysis, the mean salary for women is <code>64543</code>, but it can be anywhere between <code>61486</code> and <code>67599</code>. On the other hand, the mean salary for men is <code>73239</code>, but it can be anywhere between <code>70088</code> and <code>76390</code>. When visualising the two confidence intervals, we can also see that the two does not overlap. Hence, we can conclude that there is a significant difference between the salaries of the men and women executives, where women has a lower average salary than men.</em></p>
</div>
<div id="hypothesis-testing" class="section level3">
<h3>Hypothesis Testing</h3>
<p><em>To perform a hypothesis testing, we assume the null hypothesis (H<sub>0</sub>) that there is no difference in mean salary between men and women (difference is zero), and the alternative Hypothesis (H<sub>a</sub>) that there is a difference in mean salary between men and women (difference is non-zero).</em></p>
<p><em>We will be performing our hypothesis testing using <code>t.test()</code> and with the simulation method from the <code>infer</code> package.</em></p>
<div id="t.test" class="section level4">
<h4><code>t.test()</code></h4>
<pre class="r"><code>mosaic::favstats(salary ~ gender, data = omega)</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code>t.test(salary ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salary by gender
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean in group female   mean in group male 
##                64543                73239</code></pre>
<p><em>Interpretation: When running the hypothesis test using <code>t.test()</code>, we get a t-stat value of -4, which is greater than the 5% critical value of 1.96. Another way to look at it is that the CI for the difference between the two means is <code>[-12973, -4420]</code> which does not contains zero. Hence, we can reject the null hypothesis and conclude that there is a significant difference between the salaries of male and female executives</em>.</p>
</div>
<div id="simulation-method-infer-package" class="section level4">
<h4>Simulation Method (<code>infer</code> package)</h4>
<pre class="r"><code>set.seed(1234)

# calculate the observed statistic
observed_statistic_salary &lt;- omega %&gt;%  
  specify(salary ~ gender) %&gt;% 
  calculate(stat = &quot;diff in means&quot;,
            order = c(&quot;male&quot;, &quot;female&quot;))

observed_statistic_salary

# generate the null distribution with randomisation
diff_salary_null_world &lt;- omega %&gt;% 
  specify(salary ~ gender) %&gt;% 
  hypothesize(null = &quot;independence&quot;) %&gt;% 
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;% 
  calculate(stat = &quot;diff in means&quot;,
  order = c(&quot;male&quot;, &quot;female&quot;))

# visualise the randomisation-based null distribution and test statistic
diff_salary_null_world %&gt;% 
  visualize() +
  theme_bw()+
  shade_p_value(observed_statistic_salary, direction = &quot;two-sided&quot;) +
  scale_x_continuous(labels = number)</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/hypothesis_testing_infer_salary-1.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code>  theme_bw() + 
  labs(title = &quot;Differences in mean salaries between male and female in a hypothetical null world&quot;,
       subtitle = &quot;Red line shows observed difference in mean salaries&quot;,
       x = &quot;Difference in mean salaries\n(Male - Female)&quot;,
       y = &quot;Count&quot;) 
  

# calculate the p value from the randomisation-based null distribution and the observed statistic
p_value_salary &lt;- diff_salary_null_world %&gt;%
  get_pvalue(obs_stat = observed_statistic_salary,
              direction = &quot;two-sided&quot;)

p_value_salary</code></pre>
<p><em>Interpretation: Based on our hypothesis testing using the infer package, we get a p-value of close to 0. This means that there’s a close to 0% chance of seeing a difference at least as large as 8696 in a world where there’s no difference. In other words, given what we observed, the null hypothesis is false and it will be impossible to observed such results if the null hypothesis is true. Hence, we can reject the null world and conclude that there is a significant difference between the salaries of male and female executives.</em></p>
</div>
</div>
<div id="conclusion" class="section level3">
<h3>Conclusion</h3>
<p><em>The results of both analyses, confidence intervals and hypothesis testing, lead to the same conclusion. That is, there is a significant difference between the salaries of the male and female executives.</em></p>
</div>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship (Experience - Gender)</h2>
<p>At the board meeting, someone raised the issue that there was indeed a substantial difference between male and female salaries, but that this was attributable to other reasons such as differences in experience. A questionnaire send out to the 50 executives in the sample reveals that the average experience of the men is approximately 21 years, whereas the women only have about 7 years experience on average (see table below).</p>
<pre class="r"><code># Summary Statistics of experience by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<p><strong>Based on this evidence, can you conclude that there is a significant difference between the experience of the male and female executives?</strong></p>
<p><em>We will be performing similar analyses as in the previous section - (1) Confidence Intervals and (2) Hypothesis Testing. Let’s see how the conclusion of these analyses validates or endanger our previous conclusion on the difference in male and female salaries.</em></p>
<div id="two-separate-confidence-intervals-1" class="section level3">
<h3>Two Separate Confidence Intervals</h3>
<pre class="r"><code>formula_ci_experience &lt;- omega %&gt;% 
  group_by(gender) %&gt;% 
  summarise(mean_experience = mean(experience),
            sd_experience = sd(experience),
            count = n(),
            
            # get t-critical value with (n-1) degrees of freedom
            t_critical = qt(0.975, count-1),
            se = sd_experience/sqrt(count),
            margin_of_error = t_critical * se,
            ci_low = mean_experience - margin_of_error,
            ci_high = mean_experience + margin_of_error
            ) 

formula_ci_experience</code></pre>
<pre><code>## # A tibble: 2 × 9
##   gender mean_experience sd_experience count t_critical    se margin_of_error
##   &lt;chr&gt;            &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt;      &lt;dbl&gt; &lt;dbl&gt;           &lt;dbl&gt;
## 1 female            7.38          8.51    26       2.06  1.67            3.44
## 2 male             21.1          10.9     24       2.07  2.23            4.61
## # … with 2 more variables: ci_low &lt;dbl&gt;, ci_high &lt;dbl&gt;</code></pre>
<pre class="r"><code>ggplot(formula_ci_experience, 
       aes(x=mean_experience,
           y=gender,
           colour=gender)) +   
  geom_point() +
  scale_colour_manual(values = c(&quot;red&quot;,&quot;blue&quot;)) +
  geom_errorbar(width=.2, aes(xmax = ci_high, xmin = ci_low)) +
  theme_bw() +
  labs(title = &quot;Which gender has more years of experience?&quot;, 
       x = &quot;Average years of experience&quot;, 
       y = &quot;Gender&quot;) +
  NULL</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/visualise_ci_experience-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p><em>Interpretation: In this analysis, we compared the confidence intervals for the average years of experience of men and women to determine whether the difference between the two means is statistically significant. Based on our analysis, the average years of experience for women is around <code>7 years</code>, but it can be anywhere between <code>3.95</code> and <code>10.8 years</code>. On the other hand, the average years of experience for men is around <code>21 years</code>, but it can be anywhere between <code>16.52</code> and <code>25.7 years</code>. When visualising the two confidence intervals, we can also see that the two does not overlap. Hence, we can conclude that there is a significant difference between the experience of the male and female executives, where females have less experience than males.</em></p>
</div>
<div id="hypothesis-testing-1" class="section level3">
<h3>Hypothesis Testing</h3>
<p><em>To perform a hypothesis testing, we assume the null hypothesis (H<sub>0</sub>) that there is no difference in average experience between men and women (difference is zero), and the alternative Hypothesis (H<sub>a</sub>) that there is a difference in average experience between men and women (difference is non-zero).</em></p>
<p><em>We will be performing our hypothesis testing using <code>t.test()</code> and with the simulation method from the <code>infer</code> package.</em></p>
<div id="t.test-1" class="section level4">
<h4><code>t.test()</code></h4>
<pre class="r"><code>mosaic::favstats(experience ~ gender, data = omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<pre class="r"><code>t.test(experience ~ gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  experience by gender
## t = -5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -19.35  -8.13
## sample estimates:
## mean in group female   mean in group male 
##                 7.38                21.12</code></pre>
<p><em>Interpretation: When running the hypothesis test using <code>t.test()</code>, we get a t-stat value of -5, which is greater than the 5% critical value of 1.96. Another way to look at it is that the CI for the difference between the two means is [7.38, 21.12] which does not contains zero. Hence, we can reject the null hypothesis and conclude that there is a significant difference between the experience of the male and female executives.</em></p>
</div>
<div id="simulation-method-infer-package-1" class="section level4">
<h4>Simulation Method (<code>infer</code> package)</h4>
<pre class="r"><code>set.seed(1234)

# calculate the observed statistic
observed_statistic_experience &lt;- omega %&gt;%  
  specify(experience ~ gender) %&gt;% 
  calculate(stat = &quot;diff in means&quot;,
            order = c(&quot;male&quot;, &quot;female&quot;))

observed_statistic_experience</code></pre>
<pre><code>## Response: experience (numeric)
## Explanatory: gender (factor)
## # A tibble: 1 × 1
##    stat
##   &lt;dbl&gt;
## 1  13.7</code></pre>
<pre class="r"><code># generate the null distribution with randomisation
diff_experience_null_world &lt;- omega %&gt;% 
  specify(experience ~ gender) %&gt;% 
  hypothesize(null = &quot;independence&quot;) %&gt;% 
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;% 
  calculate(stat = &quot;diff in means&quot;,
  order = c(&quot;male&quot;, &quot;female&quot;))

# visualize the randomisation-based null distribution and test statistic
diff_experience_null_world %&gt;% 
  visualize() +
  shade_p_value(observed_statistic_experience, direction = &quot;two-sided&quot;) +
  theme_bw() + 
  labs(title = &quot;Differences in experience between male and female in a hypothetical null world&quot;,
       subtitle = &quot;Red line shows observed difference in average experience&quot;,
       x = &quot;Difference in average experience\n(Male - Female)&quot;,
       y = &quot;Count&quot;) </code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/hypothesis_testing_infer_experience-1.png" width="1056" style="display: block; margin: auto;" /></p>
<pre class="r"><code># calculate the p value from the randomisation-based null distribution and the observed statistic
p_value_experience &lt;- diff_experience_null_world %&gt;%
  get_pvalue(obs_stat = observed_statistic_experience,
              direction = &quot;two-sided&quot;)

p_value_experience</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p><em>Interpretation: Based on our hypothesis testing using the infer package, we get a p-value of close to 0. This means that there’s a close to 0% chance of seeing a difference at least as large as 13.7 years in a world where there’s no difference. In other words, given what we observed, the null hypothesis is false and it will be impossible to observed such results if the null hypothesis is true. Hence, we can reject the null world and conclude that there is a significant difference between the experience of the male and female executives.</em></p>
</div>
</div>
<div id="conclusion-1" class="section level3">
<h3>Conclusion</h3>
<p><em>The results of both analyses, confidence intervals and hypothesis testing, lead to the same conclusion. That is there is a significant difference between the experience of the male and female executives.</em></p>
</div>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship (Salary - Experience)</h2>
<p>Someone at the meeting argues that clearly, a more thorough analysis of the relationship between salary and experience is required before any conclusion can be drawn about whether there is any gender-based salary discrimination in the company.</p>
<p><strong>Analyse the relationship between salary and experience. Draw a scatter plot to visually inspect the data.</strong></p>
<div id="salary-vs-experience-scatter-plot" class="section level3">
<h3>Salary vs Experience Scatter Plot</h3>
<pre class="r"><code># Calculating Pearson&#39;s product-moment correlation
cor.test(omega$experience, omega$salary, method = &quot;pearson&quot;, conf.level = 0.95)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  x and y
## t = 9, df = 48, p-value = 2e-12
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.676 0.884
## sample estimates:
##   cor 
## 0.803</code></pre>
<pre class="r"><code>ggplot(omega, aes(x = experience, y = salary)) +
  geom_point() +
  geom_smooth(method = lm, col = &quot;red&quot;) +
  labs(title = &quot;The relationship between salary and experience&quot;, 
       x = &quot;Years of experience&quot;,
       y = &quot;Salary&quot;) + 
  theme_bw() +
  annotate(&quot;text&quot;, x = 7, y = 85000, col = &quot;red&quot;, size = 3,
             label = paste(&quot;Pearson r = &quot;, signif(cor(omega$experience, omega$salary),3))) +
  NULL</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/salary_exp_scatter-1.png" width="1056" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>Using <code>GGally:ggpairs()</code> to create a scatter plot and correlation matrix. Essentially, we change the order of our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the data frame to <code>ggpairs()</code> with <code>aes</code> arguments to colour by <code>gender</code> and make these plots somewhat transparent (<code>alpha  = 0.3</code>).</p>
<pre class="r"><code>omega %&gt;% 
  select(gender, experience, salary) %&gt;% #order variables they will appear in ggpairs()
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/ggpairs-1.png" width="1056" style="display: block; margin: auto;" /></p>
<p><strong>Look at the salary vs experience scatter plot. What can you infer from this plot? Explain in a couple of sentences.</strong></p>
<p><em>Interpretation: Based on our analysis, there is a positive relationship between salary and experience as the correlation coefficient is close to 1. In other words, as years of experience increases, salary increases. When categorizing the gender into different colors, we can see that more women are on the left side of the graph, indicating lesser years of experience on average. Hence, this is a good indication as of why women has a lower average salary as compared to men.</em></p>
</div>
<div id="final-conclusion" class="section level2">
<h2>Final conclusion</h2>
<p><em>According to our analysis, there is a positive relationship between salary and experience, and women has lower years of experience than men on average. Hence, the assumption that women were being discriminated in the company in the sense that the salaries were not the same for male and female executives may not be true. The substantial difference between male and female salaries is more likely attributable to differences in experience.</em></p>
</div>
</div>
<div id="challenge-1-brexit-plot." class="section level1">
<h1>Challenge 1: Brexit plot.</h1>
<pre class="r"><code>brexit_results &lt;- read_csv(here::here(&quot;data&quot;, &quot;brexit_results.csv&quot;))</code></pre>
<pre class="r"><code>adj_brexit_results &lt;- pivot_longer(brexit_results, cols = c(&quot;con_2015&quot;, &quot;lab_2015&quot;, &quot;ld_2015&quot;, &quot;ukip_2015&quot;), names_to = &quot;party&quot;, values_to = &quot;general_election_2015&quot;)

scatter_election_brexit &lt;- ggplot(adj_brexit_results, aes(x = general_election_2015, y = leave_share, color = party))+
  geom_point(size = 0.3)+
  geom_smooth(method = &quot;lm&quot;)+
  scale_color_manual(name = &quot;&quot;, values = c(&quot;#0087DC&quot;, &quot;#E4003B&quot;, &quot;#FAA61A&quot;,&quot;#70147A&quot;), labels = c(&quot;Conservative&quot;, &quot;Labour&quot;, &quot;Lib Dems&quot;, &quot;UKIP&quot;))+
  
  labs(title = &quot;How political affiliation translated to Brexit voting&quot;, x = &quot;Party % in the UK 2015 general election&quot;, y = &quot;Leave % in the 2016 Brexit referendum&quot;)+
  
  theme_bw()+
  theme(legend.position = &quot;bottom&quot;)

scatter_election_brexit</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/plot_brexit_data-1.png" width="1056" style="display: block; margin: auto;" /></p>
</div>
<div id="challenge-3gdp-components-over-time-and-among-countries" class="section level1">
<h1>Challenge 3:GDP components over time and among countries</h1>
<p>At the risk of oversimplifying things, the main components of gross domestic product, GDP are personal consumption (C), business investment (I), government spending (G) and net exports (exports - imports). You can read more about GDP and the different approaches in calculating at the <a href="https://en.wikipedia.org/wiki/Gross_domestic_product">Wikipedia GDP page</a>.</p>
<p>The GDP data we will look at is from the <a href="https://unstats.un.org/unsd/snaama/Downloads">United Nations’ National Accounts Main Aggregates Database</a>, which contains estimates of total GDP and its components for all countries from 1970 to today. We will look at how GDP and its components have changed over time, and compare different countries and how much each component contributes to that country’s GDP. The file we will work with is <a href="http://unstats.un.org/unsd/amaapi/api/file/6">GDP and its breakdown at constant 2010 prices in US Dollars</a> and it has already been saved in the Data directory. Have a look at the Excel file to see how it is structured and organised</p>
<pre class="r"><code>UN_GDP_data  &lt;-  read_excel(here::here(&quot;data&quot;, &quot;Download-GDPconstant-USD-countries.xls&quot;), # Excel filename
                sheet=&quot;Download-GDPconstant-USD-countr&quot;, # Sheet name
                skip=2) # Number of rows to skip</code></pre>
<p>The first thing you need to do is to tidy the data, as it is in wide format and you must make it into long, tidy format. Please express all figures in billions (divide values by <code>1e9</code>, or <span class="math inline">\(10^9\)</span>), and you want to rename the indicators into something shorter.</p>
<pre class="r"><code>tidy_GDP_data  &lt;-  UN_GDP_data %&gt;% 
  pivot_longer(cols = 4:51, values_to = &quot;gdp_in_billion&quot;, names_to = &quot;years&quot;) %&gt;% 
  mutate(gdp_in_billion = gdp_in_billion/10^9)

tidy_GDP_data</code></pre>
<pre><code>## # A tibble: 176,880 × 5
##    CountryID Country     IndicatorName                 years gdp_in_billion
##        &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;                         &lt;chr&gt;          &lt;dbl&gt;
##  1         4 Afghanistan Final consumption expenditure 1970            5.56
##  2         4 Afghanistan Final consumption expenditure 1971            5.33
##  3         4 Afghanistan Final consumption expenditure 1972            5.20
##  4         4 Afghanistan Final consumption expenditure 1973            5.75
##  5         4 Afghanistan Final consumption expenditure 1974            6.15
##  6         4 Afghanistan Final consumption expenditure 1975            6.32
##  7         4 Afghanistan Final consumption expenditure 1976            6.37
##  8         4 Afghanistan Final consumption expenditure 1977            6.90
##  9         4 Afghanistan Final consumption expenditure 1978            7.09
## 10         4 Afghanistan Final consumption expenditure 1979            6.92
## # … with 176,870 more rows</code></pre>
<pre class="r"><code>glimpse(tidy_GDP_data)</code></pre>
<pre><code>## Rows: 176,880
## Columns: 5
## $ CountryID      &lt;dbl&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4…
## $ Country        &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanist…
## $ IndicatorName  &lt;chr&gt; &quot;Final consumption expenditure&quot;, &quot;Final consumption exp…
## $ years          &lt;chr&gt; &quot;1970&quot;, &quot;1971&quot;, &quot;1972&quot;, &quot;1973&quot;, &quot;1974&quot;, &quot;1975&quot;, &quot;1976&quot;,…
## $ gdp_in_billion &lt;dbl&gt; 5.56, 5.33, 5.20, 5.75, 6.15, 6.32, 6.37, 6.90, 7.09, 6…</code></pre>
<pre class="r"><code>skim(tidy_GDP_data)</code></pre>
<table>
<caption>(#tab:reshape_GDP_data)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">tidy_GDP_data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">176880</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">3</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Country</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">34</td>
<td align="right">0</td>
<td align="right">220</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">IndicatorName</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">17</td>
<td align="right">88</td>
<td align="right">0</td>
<td align="right">17</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">years</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">48</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">CountryID</td>
<td align="right">0</td>
<td align="right">1.00</td>
<td align="right">439.2</td>
<td align="right">254</td>
<td align="right">4</td>
<td align="right">214.00</td>
<td align="right">440.0</td>
<td align="right">660.0</td>
<td align="right">894</td>
<td align="left">▇▇▇▇▆</td>
</tr>
<tr class="even">
<td align="left">gdp_in_billion</td>
<td align="right">15421</td>
<td align="right">0.91</td>
<td align="right">72.2</td>
<td align="right">447</td>
<td align="right">-568</td>
<td align="right">0.36</td>
<td align="right">2.5</td>
<td align="right">17.9</td>
<td align="right">17349</td>
<td align="left">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Let us compare GDP components for these 6 countries, including our own countries China, Malaysia and Spain
country_list &lt;- c(&quot;United States&quot;,&quot;Spain&quot;,&quot;China&quot;, &quot;Germany&quot;, &quot;India&quot;, &quot;Malaysia&quot;)</code></pre>
<pre class="r"><code>indicator_list &lt;- c(&quot;Gross capital formation&quot;,&quot;Imports of goods and services&quot;, &quot;General government final consumption expenditure&quot;, &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;, &quot;Exports of goods and services&quot;)

gdp_plot &lt;-tidy_GDP_data[which(tidy_GDP_data$Country %in% country_list),]
gdp_plot &lt;-gdp_plot[which(gdp_plot$IndicatorName %in% indicator_list),]
  
plot_gdp &lt;- ggplot(gdp_plot, aes(x = as.integer(years),y=gdp_in_billion))+
  geom_line(aes(color = IndicatorName))+
  facet_wrap(vars(Country))+ 
  labs(title = &quot;GDP components over time&quot;,subtitle = &#39;In constant 2010 USD&#39;, y = &quot;Billion US$&quot;, x= &quot;year&quot;)+
  scale_colour_hue(&quot;Components of GDP&quot;,labels=c(&quot;Exports &quot;,&quot;Government Expenditure&quot;,&quot;Gross capital formation&quot;,&quot;Household Expenditure&quot;,&quot;Imports&quot;))+
  theme_bw()+
  NULL
plot_gdp</code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/gdp%20component%20over%20time-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>Secondly, recall that GDP is the sum of Household Expenditure (Consumption <em>C</em>), Gross Capital Formation (business investment <em>I</em>), Government Expenditure (G) and Net Exports (exports - imports). Even though there is an indicator <code>Gross Domestic Product (GDP)</code> in your dataframe, I would like you to calculate it given its components discussed above.</p>
<blockquote>
<p>What is the % difference between what you calculated as GDP and the GDP figure included in the dataframe?</p>
</blockquote>
<p><em>gdp_diff is the % difference between the calculated GDP(gdp_sum) and the GDP figure in the dataframe. The mean of gdp_diff is -0.5%, which indicates that the GDP we calculated is slightly lower than the figure given. This is probably because the calculated one is expenditure approach while GDP figure is usually calculated by income approach or production approach. The measurement error in practice made two figures slightly off.</em></p>
<pre class="r"><code>indicator_list2 &lt;- c(&quot;Gross capital formation&quot;,&quot;Imports of goods and services&quot;, &quot;General government final consumption expenditure&quot;, &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;, &quot;Exports of goods and services&quot;, &quot;Gross Domestic Product (GDP)&quot;)

gdp_plot &lt;-tidy_GDP_data[which(tidy_GDP_data$Country %in% country_list),]
gdp_plot &lt;-gdp_plot[which(gdp_plot$IndicatorName %in% indicator_list2),]

gdp_plot2&lt;-pivot_wider(gdp_plot,names_from  = IndicatorName, values_from  = gdp_in_billion)

colnames(gdp_plot2)&lt;-c(&quot;countryID&quot;,&quot;country&quot;,&quot;years&quot;,&quot;Household_Expenditure&quot;,&quot;Government_Expenditure&quot;,&quot;Gross_Capital_Formation&quot;,&quot;Exports&quot;,&quot;Imports&quot;,&quot;gdp_origin&quot;) 

 gdp_plot2&lt;-gdp_plot2 %&gt;%
   mutate(Net_Exports = Exports-Imports, gdp_sum=Household_Expenditure +Government_Expenditure+Gross_Capital_Formation+Net_Exports,h_pro=Household_Expenditure/gdp_sum,g_pro=Government_Expenditure/gdp_sum,c_pro=Gross_Capital_Formation/gdp_sum,n_pro= Net_Exports/gdp_sum,gdp_diff=(gdp_sum/gdp_origin)-1)

skim(gdp_plot2)</code></pre>
<table>
<caption>(#tab:compare GDP)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">gdp_plot2</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">288</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">16</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">2</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">14</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">country</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">years</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">48</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<colgroup>
<col width="21%" />
<col width="9%" />
<col width="12%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="6%" />
<col width="7%" />
<col width="7%" />
<col width="8%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">countryID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">468.33</td>
<td align="right">242.21</td>
<td align="right">156.00</td>
<td align="right">276.00</td>
<td align="right">407.00</td>
<td align="right">724.00</td>
<td align="right">840.00</td>
<td align="left">▇▃▃▁▇</td>
</tr>
<tr class="even">
<td align="left">Household_Expenditure</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">1765.53</td>
<td align="right">2649.33</td>
<td align="right">9.53</td>
<td align="right">213.48</td>
<td align="right">718.46</td>
<td align="right">1847.68</td>
<td align="right">12021.14</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">Government_Expenditure</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">498.20</td>
<td align="right">678.21</td>
<td align="right">2.12</td>
<td align="right">44.32</td>
<td align="right">180.56</td>
<td align="right">591.64</td>
<td align="right">2510.14</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">Gross_Capital_Formation</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">713.84</td>
<td align="right">972.14</td>
<td align="right">3.39</td>
<td align="right">93.36</td>
<td align="right">330.50</td>
<td align="right">730.71</td>
<td align="right">4702.06</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">Exports</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">468.56</td>
<td align="right">592.57</td>
<td align="right">5.08</td>
<td align="right">56.17</td>
<td align="right">240.85</td>
<td align="right">529.75</td>
<td align="right">2513.01</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">Imports</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">491.98</td>
<td align="right">662.71</td>
<td align="right">4.59</td>
<td align="right">51.97</td>
<td align="right">233.60</td>
<td align="right">571.10</td>
<td align="right">3069.95</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="odd">
<td align="left">gdp_origin</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2943.93</td>
<td align="right">4028.73</td>
<td align="right">18.70</td>
<td align="right">350.11</td>
<td align="right">1321.16</td>
<td align="right">3295.53</td>
<td align="right">17348.63</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">Net_Exports</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">-23.42</td>
<td align="right">181.85</td>
<td align="right">-830.27</td>
<td align="right">-18.88</td>
<td align="right">1.05</td>
<td align="right">27.75</td>
<td align="right">380.67</td>
<td align="left">▁▁▁▇▁</td>
</tr>
<tr class="odd">
<td align="left">gdp_sum</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">2954.15</td>
<td align="right">4042.71</td>
<td align="right">16.90</td>
<td align="right">350.95</td>
<td align="right">1301.92</td>
<td align="right">3297.83</td>
<td align="right">17342.08</td>
<td align="left">▇▁▁▁▁</td>
</tr>
<tr class="even">
<td align="left">h_pro</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.57</td>
<td align="right">0.09</td>
<td align="right">0.36</td>
<td align="right">0.51</td>
<td align="right">0.58</td>
<td align="right">0.63</td>
<td align="right">0.72</td>
<td align="left">▂▂▅▇▃</td>
</tr>
<tr class="odd">
<td align="left">g_pro</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.15</td>
<td align="right">0.04</td>
<td align="right">0.08</td>
<td align="right">0.12</td>
<td align="right">0.14</td>
<td align="right">0.18</td>
<td align="right">0.25</td>
<td align="left">▆▇▅▆▁</td>
</tr>
<tr class="even">
<td align="left">c_pro</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.26</td>
<td align="right">0.08</td>
<td align="right">0.15</td>
<td align="right">0.21</td>
<td align="right">0.23</td>
<td align="right">0.30</td>
<td align="right">0.48</td>
<td align="left">▆▇▂▃▁</td>
</tr>
<tr class="odd">
<td align="left">n_pro</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0.02</td>
<td align="right">0.06</td>
<td align="right">-0.06</td>
<td align="right">-0.01</td>
<td align="right">0.00</td>
<td align="right">0.04</td>
<td align="right">0.27</td>
<td align="left">▇▅▂▁▁</td>
</tr>
<tr class="even">
<td align="left">gdp_diff</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">-0.01</td>
<td align="right">0.03</td>
<td align="right">-0.10</td>
<td align="right">-0.02</td>
<td align="right">0.00</td>
<td align="right">0.01</td>
<td align="right">0.07</td>
<td align="left">▁▁▇▅▁</td>
</tr>
</tbody>
</table>
<pre class="r"><code> gap_perc_plot &lt;- ggplot(gdp_plot2, aes(x = as.integer(years)))+
                                   facet_wrap(vars(country))+
                          geom_line(aes(y=h_pro,color=&quot;#339999&quot;))+
                         geom_line(aes(y=c_pro,color=&quot;#00CC00&quot;))+
                         geom_line(aes(y=g_pro,color=&quot;#FF3300&quot;))+
                         geom_line(aes(y=n_pro,color=&quot;purple&quot;))+
               # theme(panel.border = element_rect(colour = NA, fill=NA))+
                scale_y_continuous(labels = scales::percent)+
                theme_bw()+
   labs(title = &quot;GDP and its breakdown at constant 2010 prices in US Dollars &quot;, y = &quot;proportion&quot;, x= &quot;year&quot;)+
   scale_color_identity(breaks = c(&quot;#339999&quot;, &quot;#00CC00&quot;, &quot;#FF3300&quot;, &quot;purple&quot;),
                        labels = c(&quot;Household Expenditure&quot;, &quot;Gross capital formation&quot;, &quot;Government Expenditure&quot;, &quot;Net Exports&quot;),
                        guide = &quot;legend&quot;,
                        name = &quot;Legend&quot;)+
                NULL

                         
gap_perc_plot </code></pre>
<p><img src="/blogs/hw3_final_files/figure-html/gdp%20percent%20change%20over%20time-1.png" width="1056" style="display: block; margin: auto;" /></p>
<blockquote>
<p>What is this last chart telling you? Can you explain in a couple of paragraphs the different dynamic among these three countries?</p>
</blockquote>
<p><em>The last chart has displayed how percentage of investment(capital formation), consumption(household expenditure), net exports and government expenditure among GDP has changed over time for Germany, India and the United States. The patterns are indicating various characteristic of the countries’ economy.</em></p>
<p><em>As for Germany, the largest economy in Europe, the proportion of GDP components is generally stable from 1970 to 2000 with around 60% household expenditure, 20% capital expenditure, 20% government expenditure and 0% net exports. Since 2000, Net Export in Germany has exoerienced a sharp rise while household expenditure gradually fell by 5%. Compared with India and United States, an obvious characteristic of Germany’s economy is the trade surplus since 2000, which indicates the economic development is more dependent on international trade.</em></p>
<p><em>As for India,the fastest growing major economy throughout the world, we can observe a sharp fall in household expenditure since 1970 and a quick rise in capital formation since 2000, which means the engine of economic growth is switching from consumption to investment. Thanks to the broad economic liberalisation in India in 1990s, the growth in investment results from the incredible increase in foreign direct investment, and this finally benefits India’s economy.</em></p>
<p><em>As for the United States, the proportion of consumption and investment are gradually rising while government expenditure and net export are falling. Compared to the other countries, US seems like a consumption-oriented economy with values of around 70%. Since 1990, the US trade deficit has widened. A sudden decrease in 2008-2009 in investment sector might be attributed to the subprime mortgage crisis of the US.</em></p>
<p><em>We also included our own countries China, Malaysia and Spain.</em> <em>For China, unlike the other 5 countries, investment has exceeded consumption in 2004 and become the most important engine of economic growth. Net exports have been over zero since 1990. Trade surplus indicates that international trade makes up a sizeable portion of China’s overall economy. Since economic reforms began in the late 1970s, China sought to decentralize its foreign trade system to integrate itself into the international trading system. These efforts made China one of the world’s largest exporter of goods and can explain the trade surplus in the plot.</em></p>
<p><em>Moreover, the proportion of investment in Malaysia is growing fast from 1970. A possible reason is that in the 1970s, Malaysia began to imitate the four Asian Tiger economies (South Korea, Taiwan, Hong Kong and Singapore) and committed itself to a transition from being reliant on mining and agriculture to an economy that depends more on manufacturing. The sudden decrease in investment in 1997 is probably the result of Asian financial crisis. Since 1997, net exports stand for over 20% of GDP in Malaysia. Malaysian exports became the country’s primary growth engine. Malaysia now is a typical export-oriented economy.</em></p>
<p><em>Finally, the proportion of components of GDP in Spain is generally stable with government expenses gradually rising since 1970 by a total of 10%. The sudden decrease in its investment sector by 10% in 2008-2009 shows that the financial crisis also impacted Spain and made its economy plunge into a recession. The change in net export indicates that Spain managed to reverse the trade deficit which had built since 2003 and eventually attained a trade surplus in 2010.</em></p>
</div>
<div id="details" class="section level1">
<h1>Details</h1>
<ul>
<li>Who did you collaborate with: <em>Group 3 (Jiaying Chen, Yingjin He, Sabrina Seow, Kashish Solanki, Roman Vazquez Lorenzo, Maximilian Stock)</em></li>
<li>Approximately how much time did you spend on this problem set: <em>10</em></li>
<li>What, if anything, gave you the most trouble: <em>facet_grid needed some getting used to, but other than that it was mostly good. We find customizing legends to our exact needs always a little bit tedious.</em></li>
</ul>
<p><strong>Please seek out help when you need it,</strong> and remember the <a href="https://mam2022.netlify.app/syllabus/#the-15-minute-rule" target="_blank">15-minute rule</a>. You know enough R (and have enough examples of code from class and your readings) to be able to do this. If you get stuck, ask for help from others, post a question on Slack– and remember that I am here to help too!</p>
</div>
